// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commands.proto
// Protobuf C++ Version: 5.28.3

#include "commands.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace questnav {
namespace protos {
namespace commands {

inline constexpr ProtobufQuestNavCommandResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        command_id_{0u},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufQuestNavCommandResponse::ProtobufQuestNavCommandResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufQuestNavCommandResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavCommandResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavCommandResponseDefaultTypeInternal() {}
  union {
    ProtobufQuestNavCommandResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavCommandResponseDefaultTypeInternal _ProtobufQuestNavCommandResponse_default_instance_;

inline constexpr ProtobufQuestNavPoseResetPayload::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        target_pose_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufQuestNavPoseResetPayload::ProtobufQuestNavPoseResetPayload(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufQuestNavPoseResetPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavPoseResetPayloadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavPoseResetPayloadDefaultTypeInternal() {}
  union {
    ProtobufQuestNavPoseResetPayload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavPoseResetPayloadDefaultTypeInternal _ProtobufQuestNavPoseResetPayload_default_instance_;

inline constexpr ProtobufQuestNavCommand::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::questnav::protos::commands::QuestNavCommandType >(0)},
        command_id_{0u},
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufQuestNavCommand::ProtobufQuestNavCommand(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufQuestNavCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavCommandDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavCommandDefaultTypeInternal() {}
  union {
    ProtobufQuestNavCommand _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavCommandDefaultTypeInternal _ProtobufQuestNavCommand_default_instance_;
}  // namespace commands
}  // namespace protos
}  // namespace questnav
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_commands_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_commands_2eproto = nullptr;
const ::uint32_t
    TableStruct_commands_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload, _impl_.target_pose_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_.command_id_),
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_.payload_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommandResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommandResponse, _impl_.command_id_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommandResponse, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommandResponse, _impl_.error_message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload)},
        {10, -1, -1, sizeof(::questnav::protos::commands::ProtobufQuestNavCommand)},
        {22, -1, -1, sizeof(::questnav::protos::commands::ProtobufQuestNavCommandResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::questnav::protos::commands::_ProtobufQuestNavPoseResetPayload_default_instance_._instance,
    &::questnav::protos::commands::_ProtobufQuestNavCommand_default_instance_._instance,
    &::questnav::protos::commands::_ProtobufQuestNavCommandResponse_default_instance_._instance,
};
const char descriptor_table_protodef_commands_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016commands.proto\022\030questnav.protos.comman"
    "ds\032\020geometry3d.proto\"R\n ProtobufQuestNav"
    "PoseResetPayload\022.\n\013target_pose\030\001 \001(\0132\031."
    "wpi.proto.ProtobufPose3d\"\317\001\n\027ProtobufQue"
    "stNavCommand\022;\n\004type\030\001 \001(\0162-.questnav.pr"
    "otos.commands.QuestNavCommandType\022\022\n\ncom"
    "mand_id\030\002 \001(\r\022X\n\022pose_reset_payload\030\n \001("
    "\0132:.questnav.protos.commands.ProtobufQue"
    "stNavPoseResetPayloadH\000B\t\n\007payload\"]\n\037Pr"
    "otobufQuestNavCommandResponse\022\022\n\ncommand"
    "_id\030\001 \001(\r\022\017\n\007success\030\002 \001(\010\022\025\n\rerror_mess"
    "age\030\003 \001(\t*C\n\023QuestNavCommandType\022\034\n\030COMM"
    "AND_TYPE_UNSPECIFIED\020\000\022\016\n\nPOSE_RESET\020\001BC"
    "\n%gg.questnav.questnav.protos.generated\252"
    "\002\031QuestNav.Protos.Generatedb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_commands_2eproto_deps[1] =
    {
        &::descriptor_table_geometry3d_2eproto,
};
static ::absl::once_flag descriptor_table_commands_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_commands_2eproto = {
    false,
    false,
    595,
    descriptor_table_protodef_commands_2eproto,
    "commands.proto",
    &descriptor_table_commands_2eproto_once,
    descriptor_table_commands_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_commands_2eproto::offsets,
    file_level_enum_descriptors_commands_2eproto,
    file_level_service_descriptors_commands_2eproto,
};
namespace questnav {
namespace protos {
namespace commands {
const ::google::protobuf::EnumDescriptor* QuestNavCommandType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_commands_2eproto);
  return file_level_enum_descriptors_commands_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t QuestNavCommandType_internal_data_[] = {
    131072u, 0u, };
bool QuestNavCommandType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class ProtobufQuestNavPoseResetPayload::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufQuestNavPoseResetPayload>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufQuestNavPoseResetPayload, _impl_._has_bits_);
};

void ProtobufQuestNavPoseResetPayload::clear_target_pose() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.target_pose_ != nullptr) _impl_.target_pose_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
ProtobufQuestNavPoseResetPayload::ProtobufQuestNavPoseResetPayload(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavPoseResetPayload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufQuestNavPoseResetPayload::ProtobufQuestNavPoseResetPayload(
    ::google::protobuf::Arena* arena,
    const ProtobufQuestNavPoseResetPayload& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufQuestNavPoseResetPayload* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.target_pose_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufPose3d>(
                              arena, *from._impl_.target_pose_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavPoseResetPayload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufQuestNavPoseResetPayload::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.target_pose_ = {};
}
ProtobufQuestNavPoseResetPayload::~ProtobufQuestNavPoseResetPayload() {
  // @@protoc_insertion_point(destructor:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufQuestNavPoseResetPayload::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.target_pose_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufQuestNavPoseResetPayload::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufQuestNavPoseResetPayload_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufQuestNavPoseResetPayload::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufQuestNavPoseResetPayload>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufQuestNavPoseResetPayload>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufQuestNavPoseResetPayload>(), &ProtobufQuestNavPoseResetPayload::ByteSizeLong,
                &ProtobufQuestNavPoseResetPayload::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufQuestNavPoseResetPayload, _impl_._cached_size_),
            false,
        },
        &ProtobufQuestNavPoseResetPayload::kDescriptorMethods,
        &descriptor_table_commands_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufQuestNavPoseResetPayload::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ProtobufQuestNavPoseResetPayload::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufQuestNavPoseResetPayload, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::questnav::protos::commands::ProtobufQuestNavPoseResetPayload>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .wpi.proto.ProtobufPose3d target_pose = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavPoseResetPayload, _impl_.target_pose_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .wpi.proto.ProtobufPose3d target_pose = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavPoseResetPayload, _impl_.target_pose_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufPose3d>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufQuestNavPoseResetPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.target_pose_ != nullptr);
    _impl_.target_pose_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufQuestNavPoseResetPayload::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufQuestNavPoseResetPayload& this_ = static_cast<const ProtobufQuestNavPoseResetPayload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufQuestNavPoseResetPayload::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufQuestNavPoseResetPayload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufPose3d target_pose = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.target_pose_, this_._impl_.target_pose_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufQuestNavPoseResetPayload::ByteSizeLong(const MessageLite& base) {
          const ProtobufQuestNavPoseResetPayload& this_ = static_cast<const ProtobufQuestNavPoseResetPayload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufQuestNavPoseResetPayload::ByteSizeLong() const {
          const ProtobufQuestNavPoseResetPayload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .wpi.proto.ProtobufPose3d target_pose = 1;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.target_pose_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufQuestNavPoseResetPayload::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavPoseResetPayload*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavPoseResetPayload&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.target_pose_ != nullptr);
    if (_this->_impl_.target_pose_ == nullptr) {
      _this->_impl_.target_pose_ =
          ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufPose3d>(arena, *from._impl_.target_pose_);
    } else {
      _this->_impl_.target_pose_->MergeFrom(*from._impl_.target_pose_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavPoseResetPayload::CopyFrom(const ProtobufQuestNavPoseResetPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufQuestNavPoseResetPayload::InternalSwap(ProtobufQuestNavPoseResetPayload* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.target_pose_, other->_impl_.target_pose_);
}

::google::protobuf::Metadata ProtobufQuestNavPoseResetPayload::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufQuestNavCommand::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_._oneof_case_);
};

void ProtobufQuestNavCommand::set_allocated_pose_reset_payload(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* pose_reset_payload) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (pose_reset_payload) {
    ::google::protobuf::Arena* submessage_arena = pose_reset_payload->GetArena();
    if (message_arena != submessage_arena) {
      pose_reset_payload = ::google::protobuf::internal::GetOwnedMessage(message_arena, pose_reset_payload, submessage_arena);
    }
    set_has_pose_reset_payload();
    _impl_.payload_.pose_reset_payload_ = pose_reset_payload;
  }
  // @@protoc_insertion_point(field_set_allocated:questnav.protos.commands.ProtobufQuestNavCommand.pose_reset_payload)
}
ProtobufQuestNavCommand::ProtobufQuestNavCommand(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.commands.ProtobufQuestNavCommand)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavCommand::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::questnav::protos::commands::ProtobufQuestNavCommand& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

ProtobufQuestNavCommand::ProtobufQuestNavCommand(
    ::google::protobuf::Arena* arena,
    const ProtobufQuestNavCommand& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufQuestNavCommand* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, command_id_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::command_id_));
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kPoseResetPayload:
        _impl_.payload_.pose_reset_payload_ = ::google::protobuf::Message::CopyConstruct<::questnav::protos::commands::ProtobufQuestNavPoseResetPayload>(arena, *from._impl_.payload_.pose_reset_payload_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:questnav.protos.commands.ProtobufQuestNavCommand)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavCommand::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void ProtobufQuestNavCommand::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, command_id_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::command_id_));
}
ProtobufQuestNavCommand::~ProtobufQuestNavCommand() {
  // @@protoc_insertion_point(destructor:questnav.protos.commands.ProtobufQuestNavCommand)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufQuestNavCommand::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
  _impl_.~Impl_();
}

void ProtobufQuestNavCommand::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:questnav.protos.commands.ProtobufQuestNavCommand)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kPoseResetPayload: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.pose_reset_payload_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.pose_reset_payload_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufQuestNavCommand::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufQuestNavCommand_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufQuestNavCommand::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufQuestNavCommand>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufQuestNavCommand>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufQuestNavCommand>(), &ProtobufQuestNavCommand::ByteSizeLong,
                &ProtobufQuestNavCommand::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_._cached_size_),
            false,
        },
        &ProtobufQuestNavCommand::kDescriptorMethods,
        &descriptor_table_commands_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufQuestNavCommand::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 3, 1, 0, 2> ProtobufQuestNavCommand::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    10, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966780,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::questnav::protos::commands::ProtobufQuestNavCommand>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 command_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProtobufQuestNavCommand, _impl_.command_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.command_id_)}},
    // .questnav.protos.commands.QuestNavCommandType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProtobufQuestNavCommand, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .questnav.protos.commands.QuestNavCommandType type = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint32 command_id = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .questnav.protos.commands.ProtobufQuestNavPoseResetPayload pose_reset_payload = 10;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.payload_.pose_reset_payload_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::questnav::protos::commands::ProtobufQuestNavPoseResetPayload>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufQuestNavCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.commands.ProtobufQuestNavCommand)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.command_id_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.command_id_));
  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufQuestNavCommand::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufQuestNavCommand& this_ = static_cast<const ProtobufQuestNavCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufQuestNavCommand::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufQuestNavCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.commands.ProtobufQuestNavCommand)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .questnav.protos.commands.QuestNavCommandType type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          // uint32 command_id = 2;
          if (this_._internal_command_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_command_id(), target);
          }

          // .questnav.protos.commands.ProtobufQuestNavPoseResetPayload pose_reset_payload = 10;
          if (this_.payload_case() == kPoseResetPayload) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                10, *this_._impl_.payload_.pose_reset_payload_, this_._impl_.payload_.pose_reset_payload_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.commands.ProtobufQuestNavCommand)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufQuestNavCommand::ByteSizeLong(const MessageLite& base) {
          const ProtobufQuestNavCommand& this_ = static_cast<const ProtobufQuestNavCommand&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufQuestNavCommand::ByteSizeLong() const {
          const ProtobufQuestNavCommand& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:questnav.protos.commands.ProtobufQuestNavCommand)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .questnav.protos.commands.QuestNavCommandType type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
            // uint32 command_id = 2;
            if (this_._internal_command_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_command_id());
            }
          }
          switch (this_.payload_case()) {
            // .questnav.protos.commands.ProtobufQuestNavPoseResetPayload pose_reset_payload = 10;
            case kPoseResetPayload: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.pose_reset_payload_);
              break;
            }
            case PAYLOAD_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufQuestNavCommand::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavCommand*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavCommand&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.commands.ProtobufQuestNavCommand)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kPoseResetPayload: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.pose_reset_payload_ =
              ::google::protobuf::Message::CopyConstruct<::questnav::protos::commands::ProtobufQuestNavPoseResetPayload>(arena, *from._impl_.payload_.pose_reset_payload_);
        } else {
          _this->_impl_.payload_.pose_reset_payload_->MergeFrom(from._internal_pose_reset_payload());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavCommand::CopyFrom(const ProtobufQuestNavCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.commands.ProtobufQuestNavCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufQuestNavCommand::InternalSwap(ProtobufQuestNavCommand* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.command_id_)
      + sizeof(ProtobufQuestNavCommand::_impl_.command_id_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata ProtobufQuestNavCommand::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufQuestNavCommandResponse::_Internal {
 public:
};

ProtobufQuestNavCommandResponse::ProtobufQuestNavCommandResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.commands.ProtobufQuestNavCommandResponse)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavCommandResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::questnav::protos::commands::ProtobufQuestNavCommandResponse& from_msg)
      : error_message_(arena, from.error_message_),
        _cached_size_{0} {}

ProtobufQuestNavCommandResponse::ProtobufQuestNavCommandResponse(
    ::google::protobuf::Arena* arena,
    const ProtobufQuestNavCommandResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufQuestNavCommandResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, command_id_),
           offsetof(Impl_, success_) -
               offsetof(Impl_, command_id_) +
               sizeof(Impl_::success_));

  // @@protoc_insertion_point(copy_constructor:questnav.protos.commands.ProtobufQuestNavCommandResponse)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavCommandResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : error_message_(arena),
        _cached_size_{0} {}

inline void ProtobufQuestNavCommandResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_id_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, command_id_) +
               sizeof(Impl_::success_));
}
ProtobufQuestNavCommandResponse::~ProtobufQuestNavCommandResponse() {
  // @@protoc_insertion_point(destructor:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufQuestNavCommandResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.error_message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufQuestNavCommandResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufQuestNavCommandResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufQuestNavCommandResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufQuestNavCommandResponse>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufQuestNavCommandResponse>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufQuestNavCommandResponse>(), &ProtobufQuestNavCommandResponse::ByteSizeLong,
                &ProtobufQuestNavCommandResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_._cached_size_),
            false,
        },
        &ProtobufQuestNavCommandResponse::kDescriptorMethods,
        &descriptor_table_commands_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufQuestNavCommandResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 78, 2> ProtobufQuestNavCommandResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::questnav::protos::commands::ProtobufQuestNavCommandResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProtobufQuestNavCommandResponse, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.command_id_)}},
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ProtobufQuestNavCommandResponse, _impl_.success_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.success_)}},
    // string error_message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.error_message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 command_id = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.command_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string error_message = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.error_message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\70\0\0\15\0\0\0\0"
    "questnav.protos.commands.ProtobufQuestNavCommandResponse"
    "error_message"
  }},
};

PROTOBUF_NOINLINE void ProtobufQuestNavCommandResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  ::memset(&_impl_.command_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.command_id_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufQuestNavCommandResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufQuestNavCommandResponse& this_ = static_cast<const ProtobufQuestNavCommandResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufQuestNavCommandResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufQuestNavCommandResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 command_id = 1;
          if (this_._internal_command_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_command_id(), target);
          }

          // bool success = 2;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_success(), target);
          }

          // string error_message = 3;
          if (!this_._internal_error_message().empty()) {
            const std::string& _s = this_._internal_error_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "questnav.protos.commands.ProtobufQuestNavCommandResponse.error_message");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.commands.ProtobufQuestNavCommandResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufQuestNavCommandResponse::ByteSizeLong(const MessageLite& base) {
          const ProtobufQuestNavCommandResponse& this_ = static_cast<const ProtobufQuestNavCommandResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufQuestNavCommandResponse::ByteSizeLong() const {
          const ProtobufQuestNavCommandResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string error_message = 3;
            if (!this_._internal_error_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error_message());
            }
            // uint32 command_id = 1;
            if (this_._internal_command_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_command_id());
            }
            // bool success = 2;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufQuestNavCommandResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavCommandResponse*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavCommandResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_command_id() != 0) {
    _this->_impl_.command_id_ = from._impl_.command_id_;
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavCommandResponse::CopyFrom(const ProtobufQuestNavCommandResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufQuestNavCommandResponse::InternalSwap(ProtobufQuestNavCommandResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.success_)
      + sizeof(ProtobufQuestNavCommandResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.command_id_)>(
          reinterpret_cast<char*>(&_impl_.command_id_),
          reinterpret_cast<char*>(&other->_impl_.command_id_));
}

::google::protobuf::Metadata ProtobufQuestNavCommandResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace commands
}  // namespace protos
}  // namespace questnav
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_commands_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
