// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf C++ Version: 5.28.3

#include "data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace questnav {
namespace protos {
namespace data {

inline constexpr ProtobufQuestNavDeviceData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : tracking_lost_counter_{0},
        battery_percent_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufQuestNavDeviceData::ProtobufQuestNavDeviceData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufQuestNavDeviceDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavDeviceDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavDeviceDataDefaultTypeInternal() {}
  union {
    ProtobufQuestNavDeviceData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavDeviceDataDefaultTypeInternal _ProtobufQuestNavDeviceData_default_instance_;

inline constexpr ProtobufQuestNavFrameData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pose3d_{nullptr},
        timestamp_{0},
        frame_count_{0},
        istracking_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufQuestNavFrameData::ProtobufQuestNavFrameData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufQuestNavFrameDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavFrameDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavFrameDataDefaultTypeInternal() {}
  union {
    ProtobufQuestNavFrameData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavFrameDataDefaultTypeInternal _ProtobufQuestNavFrameData_default_instance_;
}  // namespace data
}  // namespace protos
}  // namespace questnav
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_data_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_data_2eproto = nullptr;
const ::uint32_t
    TableStruct_data_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_.frame_count_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_.pose3d_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_.istracking_),
        ~0u,
        ~0u,
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavDeviceData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavDeviceData, _impl_.tracking_lost_counter_),
        PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavDeviceData, _impl_.battery_percent_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::questnav::protos::data::ProtobufQuestNavFrameData)},
        {16, -1, -1, sizeof(::questnav::protos::data::ProtobufQuestNavDeviceData)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::questnav::protos::data::_ProtobufQuestNavFrameData_default_instance_._instance,
    &::questnav::protos::data::_ProtobufQuestNavDeviceData_default_instance_._instance,
};
const char descriptor_table_protodef_data_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\ndata.proto\022\024questnav.protos.data\032\020geom"
    "etry3d.proto\"\202\001\n\031ProtobufQuestNavFrameDa"
    "ta\022\023\n\013frame_count\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001"
    "(\001\022)\n\006pose3d\030\003 \001(\0132\031.wpi.proto.ProtobufP"
    "ose3d\022\022\n\nisTracking\030\004 \001(\010\"T\n\032ProtobufQue"
    "stNavDeviceData\022\035\n\025tracking_lost_counter"
    "\030\001 \001(\005\022\027\n\017battery_percent\030\003 \001(\005BC\n%gg.qu"
    "estnav.questnav.protos.generated\252\002\031Quest"
    "Nav.Protos.Generatedb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_data_2eproto_deps[1] =
    {
        &::descriptor_table_geometry3d_2eproto,
};
static ::absl::once_flag descriptor_table_data_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_data_2eproto = {
    false,
    false,
    348,
    descriptor_table_protodef_data_2eproto,
    "data.proto",
    &descriptor_table_data_2eproto_once,
    descriptor_table_data_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_data_2eproto::offsets,
    file_level_enum_descriptors_data_2eproto,
    file_level_service_descriptors_data_2eproto,
};
namespace questnav {
namespace protos {
namespace data {
// ===================================================================

class ProtobufQuestNavFrameData::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufQuestNavFrameData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_._has_bits_);
};

void ProtobufQuestNavFrameData::clear_pose3d() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pose3d_ != nullptr) _impl_.pose3d_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
ProtobufQuestNavFrameData::ProtobufQuestNavFrameData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.data.ProtobufQuestNavFrameData)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavFrameData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::questnav::protos::data::ProtobufQuestNavFrameData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufQuestNavFrameData::ProtobufQuestNavFrameData(
    ::google::protobuf::Arena* arena,
    const ProtobufQuestNavFrameData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufQuestNavFrameData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.pose3d_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufPose3d>(
                              arena, *from._impl_.pose3d_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, istracking_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::istracking_));

  // @@protoc_insertion_point(copy_constructor:questnav.protos.data.ProtobufQuestNavFrameData)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavFrameData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufQuestNavFrameData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pose3d_),
           0,
           offsetof(Impl_, istracking_) -
               offsetof(Impl_, pose3d_) +
               sizeof(Impl_::istracking_));
}
ProtobufQuestNavFrameData::~ProtobufQuestNavFrameData() {
  // @@protoc_insertion_point(destructor:questnav.protos.data.ProtobufQuestNavFrameData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufQuestNavFrameData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.pose3d_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufQuestNavFrameData::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufQuestNavFrameData_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufQuestNavFrameData::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufQuestNavFrameData>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufQuestNavFrameData>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufQuestNavFrameData>(), &ProtobufQuestNavFrameData::ByteSizeLong,
                &ProtobufQuestNavFrameData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_._cached_size_),
            false,
        },
        &ProtobufQuestNavFrameData::kDescriptorMethods,
        &descriptor_table_data_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufQuestNavFrameData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2> ProtobufQuestNavFrameData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::questnav::protos::data::ProtobufQuestNavFrameData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool isTracking = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ProtobufQuestNavFrameData, _impl_.istracking_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.istracking_)}},
    // int32 frame_count = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProtobufQuestNavFrameData, _impl_.frame_count_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.frame_count_)}},
    // double timestamp = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.timestamp_)}},
    // .wpi.proto.ProtobufPose3d pose3d = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.pose3d_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 frame_count = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.frame_count_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // double timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.timestamp_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // .wpi.proto.ProtobufPose3d pose3d = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.pose3d_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool isTracking = 4;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.istracking_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufPose3d>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufQuestNavFrameData::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.data.ProtobufQuestNavFrameData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.pose3d_ != nullptr);
    _impl_.pose3d_->Clear();
  }
  ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.istracking_) -
      reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.istracking_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufQuestNavFrameData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufQuestNavFrameData& this_ = static_cast<const ProtobufQuestNavFrameData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufQuestNavFrameData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufQuestNavFrameData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.data.ProtobufQuestNavFrameData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 frame_count = 1;
          if (this_._internal_frame_count() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_frame_count(), target);
          }

          // double timestamp = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_timestamp()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_timestamp(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufPose3d pose3d = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.pose3d_, this_._impl_.pose3d_->GetCachedSize(), target,
                stream);
          }

          // bool isTracking = 4;
          if (this_._internal_istracking() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_istracking(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.data.ProtobufQuestNavFrameData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufQuestNavFrameData::ByteSizeLong(const MessageLite& base) {
          const ProtobufQuestNavFrameData& this_ = static_cast<const ProtobufQuestNavFrameData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufQuestNavFrameData::ByteSizeLong() const {
          const ProtobufQuestNavFrameData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:questnav.protos.data.ProtobufQuestNavFrameData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .wpi.proto.ProtobufPose3d pose3d = 3;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.pose3d_);
            }
          }
           {
            // double timestamp = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_timestamp()) != 0) {
              total_size += 9;
            }
            // int32 frame_count = 1;
            if (this_._internal_frame_count() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_frame_count());
            }
            // bool isTracking = 4;
            if (this_._internal_istracking() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufQuestNavFrameData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavFrameData*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavFrameData&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.data.ProtobufQuestNavFrameData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.pose3d_ != nullptr);
    if (_this->_impl_.pose3d_ == nullptr) {
      _this->_impl_.pose3d_ =
          ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufPose3d>(arena, *from._impl_.pose3d_);
    } else {
      _this->_impl_.pose3d_->MergeFrom(*from._impl_.pose3d_);
    }
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_timestamp()) != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  if (from._internal_frame_count() != 0) {
    _this->_impl_.frame_count_ = from._impl_.frame_count_;
  }
  if (from._internal_istracking() != 0) {
    _this->_impl_.istracking_ = from._impl_.istracking_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavFrameData::CopyFrom(const ProtobufQuestNavFrameData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.data.ProtobufQuestNavFrameData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufQuestNavFrameData::InternalSwap(ProtobufQuestNavFrameData* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.istracking_)
      + sizeof(ProtobufQuestNavFrameData::_impl_.istracking_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.pose3d_)>(
          reinterpret_cast<char*>(&_impl_.pose3d_),
          reinterpret_cast<char*>(&other->_impl_.pose3d_));
}

::google::protobuf::Metadata ProtobufQuestNavFrameData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufQuestNavDeviceData::_Internal {
 public:
};

ProtobufQuestNavDeviceData::ProtobufQuestNavDeviceData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.data.ProtobufQuestNavDeviceData)
}
ProtobufQuestNavDeviceData::ProtobufQuestNavDeviceData(
    ::google::protobuf::Arena* arena, const ProtobufQuestNavDeviceData& from)
    : ProtobufQuestNavDeviceData(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuestNavDeviceData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufQuestNavDeviceData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, tracking_lost_counter_),
           0,
           offsetof(Impl_, battery_percent_) -
               offsetof(Impl_, tracking_lost_counter_) +
               sizeof(Impl_::battery_percent_));
}
ProtobufQuestNavDeviceData::~ProtobufQuestNavDeviceData() {
  // @@protoc_insertion_point(destructor:questnav.protos.data.ProtobufQuestNavDeviceData)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufQuestNavDeviceData::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufQuestNavDeviceData::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufQuestNavDeviceData_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufQuestNavDeviceData::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufQuestNavDeviceData>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufQuestNavDeviceData>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufQuestNavDeviceData>(), &ProtobufQuestNavDeviceData::ByteSizeLong,
                &ProtobufQuestNavDeviceData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_._cached_size_),
            false,
        },
        &ProtobufQuestNavDeviceData::kDescriptorMethods,
        &descriptor_table_data_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufQuestNavDeviceData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 2, 0, 0, 2> ProtobufQuestNavDeviceData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967290,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::questnav::protos::data::ProtobufQuestNavDeviceData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 tracking_lost_counter = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProtobufQuestNavDeviceData, _impl_.tracking_lost_counter_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_.tracking_lost_counter_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // int32 battery_percent = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProtobufQuestNavDeviceData, _impl_.battery_percent_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_.battery_percent_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 tracking_lost_counter = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_.tracking_lost_counter_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 battery_percent = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_.battery_percent_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ProtobufQuestNavDeviceData::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.data.ProtobufQuestNavDeviceData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.tracking_lost_counter_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.battery_percent_) -
      reinterpret_cast<char*>(&_impl_.tracking_lost_counter_)) + sizeof(_impl_.battery_percent_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufQuestNavDeviceData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufQuestNavDeviceData& this_ = static_cast<const ProtobufQuestNavDeviceData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufQuestNavDeviceData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufQuestNavDeviceData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.data.ProtobufQuestNavDeviceData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 tracking_lost_counter = 1;
          if (this_._internal_tracking_lost_counter() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_tracking_lost_counter(), target);
          }

          // int32 battery_percent = 3;
          if (this_._internal_battery_percent() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_battery_percent(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.data.ProtobufQuestNavDeviceData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufQuestNavDeviceData::ByteSizeLong(const MessageLite& base) {
          const ProtobufQuestNavDeviceData& this_ = static_cast<const ProtobufQuestNavDeviceData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufQuestNavDeviceData::ByteSizeLong() const {
          const ProtobufQuestNavDeviceData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:questnav.protos.data.ProtobufQuestNavDeviceData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 tracking_lost_counter = 1;
            if (this_._internal_tracking_lost_counter() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_tracking_lost_counter());
            }
            // int32 battery_percent = 3;
            if (this_._internal_battery_percent() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_battery_percent());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufQuestNavDeviceData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavDeviceData*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavDeviceData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.data.ProtobufQuestNavDeviceData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_tracking_lost_counter() != 0) {
    _this->_impl_.tracking_lost_counter_ = from._impl_.tracking_lost_counter_;
  }
  if (from._internal_battery_percent() != 0) {
    _this->_impl_.battery_percent_ = from._impl_.battery_percent_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavDeviceData::CopyFrom(const ProtobufQuestNavDeviceData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.data.ProtobufQuestNavDeviceData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufQuestNavDeviceData::InternalSwap(ProtobufQuestNavDeviceData* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_.battery_percent_)
      + sizeof(ProtobufQuestNavDeviceData::_impl_.battery_percent_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_.tracking_lost_counter_)>(
          reinterpret_cast<char*>(&_impl_.tracking_lost_counter_),
          reinterpret_cast<char*>(&other->_impl_.tracking_lost_counter_));
}

::google::protobuf::Metadata ProtobufQuestNavDeviceData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace protos
}  // namespace questnav
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_data_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
