// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: geometry3d.proto
// Protobuf C++ Version: 5.28.3

#include "geometry3d.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace wpi {
namespace proto {

inline constexpr ProtobufTwist3d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dx_{0},
        dy_{0},
        dz_{0},
        rx_{0},
        ry_{0},
        rz_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufTwist3d::ProtobufTwist3d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufTwist3dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufTwist3dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufTwist3dDefaultTypeInternal() {}
  union {
    ProtobufTwist3d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufTwist3dDefaultTypeInternal _ProtobufTwist3d_default_instance_;

inline constexpr ProtobufTranslation3d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufTranslation3d::ProtobufTranslation3d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufTranslation3dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufTranslation3dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufTranslation3dDefaultTypeInternal() {}
  union {
    ProtobufTranslation3d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufTranslation3dDefaultTypeInternal _ProtobufTranslation3d_default_instance_;

inline constexpr ProtobufQuaternion::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : w_{0},
        x_{0},
        y_{0},
        z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufQuaternion::ProtobufQuaternion(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufQuaternionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuaternionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuaternionDefaultTypeInternal() {}
  union {
    ProtobufQuaternion _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuaternionDefaultTypeInternal _ProtobufQuaternion_default_instance_;

inline constexpr ProtobufRotation3d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        q_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufRotation3d::ProtobufRotation3d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufRotation3dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufRotation3dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufRotation3dDefaultTypeInternal() {}
  union {
    ProtobufRotation3d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufRotation3dDefaultTypeInternal _ProtobufRotation3d_default_instance_;

inline constexpr ProtobufTransform3d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        translation_{nullptr},
        rotation_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufTransform3d::ProtobufTransform3d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufTransform3dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufTransform3dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufTransform3dDefaultTypeInternal() {}
  union {
    ProtobufTransform3d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufTransform3dDefaultTypeInternal _ProtobufTransform3d_default_instance_;

inline constexpr ProtobufPose3d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        translation_{nullptr},
        rotation_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufPose3d::ProtobufPose3d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufPose3dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufPose3dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufPose3dDefaultTypeInternal() {}
  union {
    ProtobufPose3d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufPose3dDefaultTypeInternal _ProtobufPose3d_default_instance_;
}  // namespace proto
}  // namespace wpi
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_geometry3d_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_geometry3d_2eproto = nullptr;
const ::uint32_t
    TableStruct_geometry3d_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTranslation3d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTranslation3d, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTranslation3d, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTranslation3d, _impl_.z_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufQuaternion, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufQuaternion, _impl_.w_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufQuaternion, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufQuaternion, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufQuaternion, _impl_.z_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRotation3d, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRotation3d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRotation3d, _impl_.q_),
        0,
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufPose3d, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufPose3d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufPose3d, _impl_.translation_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufPose3d, _impl_.rotation_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTransform3d, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTransform3d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTransform3d, _impl_.translation_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTransform3d, _impl_.rotation_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist3d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist3d, _impl_.dx_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist3d, _impl_.dy_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist3d, _impl_.dz_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist3d, _impl_.rx_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist3d, _impl_.ry_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist3d, _impl_.rz_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::wpi::proto::ProtobufTranslation3d)},
        {11, -1, -1, sizeof(::wpi::proto::ProtobufQuaternion)},
        {23, 32, -1, sizeof(::wpi::proto::ProtobufRotation3d)},
        {33, 43, -1, sizeof(::wpi::proto::ProtobufPose3d)},
        {45, 55, -1, sizeof(::wpi::proto::ProtobufTransform3d)},
        {57, -1, -1, sizeof(::wpi::proto::ProtobufTwist3d)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::wpi::proto::_ProtobufTranslation3d_default_instance_._instance,
    &::wpi::proto::_ProtobufQuaternion_default_instance_._instance,
    &::wpi::proto::_ProtobufRotation3d_default_instance_._instance,
    &::wpi::proto::_ProtobufPose3d_default_instance_._instance,
    &::wpi::proto::_ProtobufTransform3d_default_instance_._instance,
    &::wpi::proto::_ProtobufTwist3d_default_instance_._instance,
};
const char descriptor_table_protodef_geometry3d_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020geometry3d.proto\022\twpi.proto\"8\n\025Protobu"
    "fTranslation3d\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001"
    "z\030\003 \001(\001\"@\n\022ProtobufQuaternion\022\t\n\001w\030\001 \001(\001"
    "\022\t\n\001x\030\002 \001(\001\022\t\n\001y\030\003 \001(\001\022\t\n\001z\030\004 \001(\001\">\n\022Pro"
    "tobufRotation3d\022(\n\001q\030\001 \001(\0132\035.wpi.proto.P"
    "rotobufQuaternion\"x\n\016ProtobufPose3d\0225\n\013t"
    "ranslation\030\001 \001(\0132 .wpi.proto.ProtobufTra"
    "nslation3d\022/\n\010rotation\030\002 \001(\0132\035.wpi.proto"
    ".ProtobufRotation3d\"}\n\023ProtobufTransform"
    "3d\0225\n\013translation\030\001 \001(\0132 .wpi.proto.Prot"
    "obufTranslation3d\022/\n\010rotation\030\002 \001(\0132\035.wp"
    "i.proto.ProtobufRotation3d\"Y\n\017ProtobufTw"
    "ist3d\022\n\n\002dx\030\001 \001(\001\022\n\n\002dy\030\002 \001(\001\022\n\n\002dz\030\003 \001("
    "\001\022\n\n\002rx\030\004 \001(\001\022\n\n\002ry\030\005 \001(\001\022\n\n\002rz\030\006 \001(\001B\032\n"
    "\030edu.wpi.first.math.protob\006proto3"
};
static ::absl::once_flag descriptor_table_geometry3d_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_geometry3d_2eproto = {
    false,
    false,
    593,
    descriptor_table_protodef_geometry3d_2eproto,
    "geometry3d.proto",
    &descriptor_table_geometry3d_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_geometry3d_2eproto::offsets,
    file_level_enum_descriptors_geometry3d_2eproto,
    file_level_service_descriptors_geometry3d_2eproto,
};
namespace wpi {
namespace proto {
// ===================================================================

class ProtobufTranslation3d::_Internal {
 public:
};

ProtobufTranslation3d::ProtobufTranslation3d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufTranslation3d)
}
ProtobufTranslation3d::ProtobufTranslation3d(
    ::google::protobuf::Arena* arena, const ProtobufTranslation3d& from)
    : ProtobufTranslation3d(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ProtobufTranslation3d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufTranslation3d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
ProtobufTranslation3d::~ProtobufTranslation3d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufTranslation3d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufTranslation3d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufTranslation3d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufTranslation3d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufTranslation3d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufTranslation3d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufTranslation3d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufTranslation3d>(), &ProtobufTranslation3d::ByteSizeLong,
                &ProtobufTranslation3d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_._cached_size_),
            false,
        },
        &ProtobufTranslation3d::kDescriptorMethods,
        &descriptor_table_geometry3d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufTranslation3d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ProtobufTranslation3d::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTranslation3d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double x = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_.x_)}},
    // double y = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_.y_)}},
    // double z = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double x = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double y = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double z = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_.z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ProtobufTranslation3d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufTranslation3d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufTranslation3d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufTranslation3d& this_ = static_cast<const ProtobufTranslation3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufTranslation3d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufTranslation3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufTranslation3d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double x = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_x(), target);
          }

          // double y = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_y(), target);
          }

          // double z = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_z(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufTranslation3d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufTranslation3d::ByteSizeLong(const MessageLite& base) {
          const ProtobufTranslation3d& this_ = static_cast<const ProtobufTranslation3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufTranslation3d::ByteSizeLong() const {
          const ProtobufTranslation3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufTranslation3d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double x = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_x()) != 0) {
              total_size += 9;
            }
            // double y = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_y()) != 0) {
              total_size += 9;
            }
            // double z = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_z()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufTranslation3d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufTranslation3d*>(&to_msg);
  auto& from = static_cast<const ProtobufTranslation3d&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufTranslation3d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_z()) != 0) {
    _this->_impl_.z_ = from._impl_.z_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufTranslation3d::CopyFrom(const ProtobufTranslation3d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufTranslation3d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufTranslation3d::InternalSwap(ProtobufTranslation3d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_.z_)
      + sizeof(ProtobufTranslation3d::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(ProtobufTranslation3d, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata ProtobufTranslation3d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufQuaternion::_Internal {
 public:
};

ProtobufQuaternion::ProtobufQuaternion(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufQuaternion)
}
ProtobufQuaternion::ProtobufQuaternion(
    ::google::protobuf::Arena* arena, const ProtobufQuaternion& from)
    : ProtobufQuaternion(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ProtobufQuaternion::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufQuaternion::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, w_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, w_) +
               sizeof(Impl_::z_));
}
ProtobufQuaternion::~ProtobufQuaternion() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufQuaternion)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufQuaternion::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufQuaternion::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufQuaternion_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufQuaternion::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufQuaternion>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufQuaternion>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufQuaternion>(), &ProtobufQuaternion::ByteSizeLong,
                &ProtobufQuaternion::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_._cached_size_),
            false,
        },
        &ProtobufQuaternion::kDescriptorMethods,
        &descriptor_table_geometry3d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufQuaternion::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> ProtobufQuaternion::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufQuaternion>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double z = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.z_)}},
    // double w = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.w_)}},
    // double x = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.x_)}},
    // double y = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.y_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double w = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.w_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double x = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double y = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double z = 4;
    {PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ProtobufQuaternion::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufQuaternion)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.w_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.w_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufQuaternion::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufQuaternion& this_ = static_cast<const ProtobufQuaternion&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufQuaternion::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufQuaternion& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufQuaternion)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double w = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_w()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_w(), target);
          }

          // double x = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_x(), target);
          }

          // double y = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_y(), target);
          }

          // double z = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_z(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufQuaternion)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufQuaternion::ByteSizeLong(const MessageLite& base) {
          const ProtobufQuaternion& this_ = static_cast<const ProtobufQuaternion&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufQuaternion::ByteSizeLong() const {
          const ProtobufQuaternion& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufQuaternion)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double w = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_w()) != 0) {
              total_size += 9;
            }
            // double x = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_x()) != 0) {
              total_size += 9;
            }
            // double y = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_y()) != 0) {
              total_size += 9;
            }
            // double z = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_z()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufQuaternion::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufQuaternion*>(&to_msg);
  auto& from = static_cast<const ProtobufQuaternion&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufQuaternion)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_w()) != 0) {
    _this->_impl_.w_ = from._impl_.w_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_z()) != 0) {
    _this->_impl_.z_ = from._impl_.z_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuaternion::CopyFrom(const ProtobufQuaternion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufQuaternion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufQuaternion::InternalSwap(ProtobufQuaternion* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.z_)
      + sizeof(ProtobufQuaternion::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuaternion, _impl_.w_)>(
          reinterpret_cast<char*>(&_impl_.w_),
          reinterpret_cast<char*>(&other->_impl_.w_));
}

::google::protobuf::Metadata ProtobufQuaternion::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufRotation3d::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufRotation3d>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufRotation3d, _impl_._has_bits_);
};

ProtobufRotation3d::ProtobufRotation3d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufRotation3d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufRotation3d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::wpi::proto::ProtobufRotation3d& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufRotation3d::ProtobufRotation3d(
    ::google::protobuf::Arena* arena,
    const ProtobufRotation3d& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufRotation3d* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.q_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufQuaternion>(
                              arena, *from._impl_.q_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:wpi.proto.ProtobufRotation3d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufRotation3d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufRotation3d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.q_ = {};
}
ProtobufRotation3d::~ProtobufRotation3d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufRotation3d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufRotation3d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.q_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufRotation3d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufRotation3d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufRotation3d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufRotation3d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufRotation3d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufRotation3d>(), &ProtobufRotation3d::ByteSizeLong,
                &ProtobufRotation3d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufRotation3d, _impl_._cached_size_),
            false,
        },
        &ProtobufRotation3d::kDescriptorMethods,
        &descriptor_table_geometry3d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufRotation3d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ProtobufRotation3d::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufRotation3d, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufRotation3d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .wpi.proto.ProtobufQuaternion q = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufRotation3d, _impl_.q_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .wpi.proto.ProtobufQuaternion q = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufRotation3d, _impl_.q_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufQuaternion>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufRotation3d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufRotation3d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.q_ != nullptr);
    _impl_.q_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufRotation3d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufRotation3d& this_ = static_cast<const ProtobufRotation3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufRotation3d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufRotation3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufRotation3d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufQuaternion q = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.q_, this_._impl_.q_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufRotation3d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufRotation3d::ByteSizeLong(const MessageLite& base) {
          const ProtobufRotation3d& this_ = static_cast<const ProtobufRotation3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufRotation3d::ByteSizeLong() const {
          const ProtobufRotation3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufRotation3d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .wpi.proto.ProtobufQuaternion q = 1;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.q_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufRotation3d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufRotation3d*>(&to_msg);
  auto& from = static_cast<const ProtobufRotation3d&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufRotation3d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.q_ != nullptr);
    if (_this->_impl_.q_ == nullptr) {
      _this->_impl_.q_ =
          ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufQuaternion>(arena, *from._impl_.q_);
    } else {
      _this->_impl_.q_->MergeFrom(*from._impl_.q_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufRotation3d::CopyFrom(const ProtobufRotation3d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufRotation3d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufRotation3d::InternalSwap(ProtobufRotation3d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.q_, other->_impl_.q_);
}

::google::protobuf::Metadata ProtobufRotation3d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufPose3d::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufPose3d>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_._has_bits_);
};

ProtobufPose3d::ProtobufPose3d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufPose3d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufPose3d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::wpi::proto::ProtobufPose3d& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufPose3d::ProtobufPose3d(
    ::google::protobuf::Arena* arena,
    const ProtobufPose3d& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufPose3d* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.translation_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufTranslation3d>(
                              arena, *from._impl_.translation_)
                        : nullptr;
  _impl_.rotation_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufRotation3d>(
                              arena, *from._impl_.rotation_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:wpi.proto.ProtobufPose3d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufPose3d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufPose3d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, translation_),
           0,
           offsetof(Impl_, rotation_) -
               offsetof(Impl_, translation_) +
               sizeof(Impl_::rotation_));
}
ProtobufPose3d::~ProtobufPose3d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufPose3d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufPose3d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.translation_;
  delete _impl_.rotation_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufPose3d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufPose3d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufPose3d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufPose3d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufPose3d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufPose3d>(), &ProtobufPose3d::ByteSizeLong,
                &ProtobufPose3d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_._cached_size_),
            false,
        },
        &ProtobufPose3d::kDescriptorMethods,
        &descriptor_table_geometry3d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufPose3d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> ProtobufPose3d::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufPose3d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .wpi.proto.ProtobufRotation3d rotation = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_.rotation_)}},
    // .wpi.proto.ProtobufTranslation3d translation = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_.translation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .wpi.proto.ProtobufTranslation3d translation = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_.translation_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .wpi.proto.ProtobufRotation3d rotation = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_.rotation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTranslation3d>()},
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufRotation3d>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufPose3d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufPose3d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.translation_ != nullptr);
      _impl_.translation_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.rotation_ != nullptr);
      _impl_.rotation_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufPose3d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufPose3d& this_ = static_cast<const ProtobufPose3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufPose3d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufPose3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufPose3d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufTranslation3d translation = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.translation_, this_._impl_.translation_->GetCachedSize(), target,
                stream);
          }

          // .wpi.proto.ProtobufRotation3d rotation = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.rotation_, this_._impl_.rotation_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufPose3d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufPose3d::ByteSizeLong(const MessageLite& base) {
          const ProtobufPose3d& this_ = static_cast<const ProtobufPose3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufPose3d::ByteSizeLong() const {
          const ProtobufPose3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufPose3d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .wpi.proto.ProtobufTranslation3d translation = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.translation_);
            }
            // .wpi.proto.ProtobufRotation3d rotation = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rotation_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufPose3d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufPose3d*>(&to_msg);
  auto& from = static_cast<const ProtobufPose3d&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufPose3d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.translation_ != nullptr);
      if (_this->_impl_.translation_ == nullptr) {
        _this->_impl_.translation_ =
            ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufTranslation3d>(arena, *from._impl_.translation_);
      } else {
        _this->_impl_.translation_->MergeFrom(*from._impl_.translation_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.rotation_ != nullptr);
      if (_this->_impl_.rotation_ == nullptr) {
        _this->_impl_.rotation_ =
            ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufRotation3d>(arena, *from._impl_.rotation_);
      } else {
        _this->_impl_.rotation_->MergeFrom(*from._impl_.rotation_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufPose3d::CopyFrom(const ProtobufPose3d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufPose3d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufPose3d::InternalSwap(ProtobufPose3d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_.rotation_)
      + sizeof(ProtobufPose3d::_impl_.rotation_)
      - PROTOBUF_FIELD_OFFSET(ProtobufPose3d, _impl_.translation_)>(
          reinterpret_cast<char*>(&_impl_.translation_),
          reinterpret_cast<char*>(&other->_impl_.translation_));
}

::google::protobuf::Metadata ProtobufPose3d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufTransform3d::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufTransform3d>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_._has_bits_);
};

ProtobufTransform3d::ProtobufTransform3d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufTransform3d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufTransform3d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::wpi::proto::ProtobufTransform3d& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufTransform3d::ProtobufTransform3d(
    ::google::protobuf::Arena* arena,
    const ProtobufTransform3d& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufTransform3d* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.translation_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufTranslation3d>(
                              arena, *from._impl_.translation_)
                        : nullptr;
  _impl_.rotation_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufRotation3d>(
                              arena, *from._impl_.rotation_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:wpi.proto.ProtobufTransform3d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufTransform3d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufTransform3d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, translation_),
           0,
           offsetof(Impl_, rotation_) -
               offsetof(Impl_, translation_) +
               sizeof(Impl_::rotation_));
}
ProtobufTransform3d::~ProtobufTransform3d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufTransform3d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufTransform3d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.translation_;
  delete _impl_.rotation_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufTransform3d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufTransform3d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufTransform3d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufTransform3d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufTransform3d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufTransform3d>(), &ProtobufTransform3d::ByteSizeLong,
                &ProtobufTransform3d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_._cached_size_),
            false,
        },
        &ProtobufTransform3d::kDescriptorMethods,
        &descriptor_table_geometry3d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufTransform3d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> ProtobufTransform3d::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTransform3d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .wpi.proto.ProtobufRotation3d rotation = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_.rotation_)}},
    // .wpi.proto.ProtobufTranslation3d translation = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_.translation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .wpi.proto.ProtobufTranslation3d translation = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_.translation_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .wpi.proto.ProtobufRotation3d rotation = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_.rotation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTranslation3d>()},
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufRotation3d>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufTransform3d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufTransform3d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.translation_ != nullptr);
      _impl_.translation_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.rotation_ != nullptr);
      _impl_.rotation_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufTransform3d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufTransform3d& this_ = static_cast<const ProtobufTransform3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufTransform3d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufTransform3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufTransform3d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufTranslation3d translation = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.translation_, this_._impl_.translation_->GetCachedSize(), target,
                stream);
          }

          // .wpi.proto.ProtobufRotation3d rotation = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.rotation_, this_._impl_.rotation_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufTransform3d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufTransform3d::ByteSizeLong(const MessageLite& base) {
          const ProtobufTransform3d& this_ = static_cast<const ProtobufTransform3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufTransform3d::ByteSizeLong() const {
          const ProtobufTransform3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufTransform3d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .wpi.proto.ProtobufTranslation3d translation = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.translation_);
            }
            // .wpi.proto.ProtobufRotation3d rotation = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rotation_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufTransform3d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufTransform3d*>(&to_msg);
  auto& from = static_cast<const ProtobufTransform3d&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufTransform3d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.translation_ != nullptr);
      if (_this->_impl_.translation_ == nullptr) {
        _this->_impl_.translation_ =
            ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufTranslation3d>(arena, *from._impl_.translation_);
      } else {
        _this->_impl_.translation_->MergeFrom(*from._impl_.translation_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.rotation_ != nullptr);
      if (_this->_impl_.rotation_ == nullptr) {
        _this->_impl_.rotation_ =
            ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufRotation3d>(arena, *from._impl_.rotation_);
      } else {
        _this->_impl_.rotation_->MergeFrom(*from._impl_.rotation_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufTransform3d::CopyFrom(const ProtobufTransform3d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufTransform3d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufTransform3d::InternalSwap(ProtobufTransform3d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_.rotation_)
      + sizeof(ProtobufTransform3d::_impl_.rotation_)
      - PROTOBUF_FIELD_OFFSET(ProtobufTransform3d, _impl_.translation_)>(
          reinterpret_cast<char*>(&_impl_.translation_),
          reinterpret_cast<char*>(&other->_impl_.translation_));
}

::google::protobuf::Metadata ProtobufTransform3d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufTwist3d::_Internal {
 public:
};

ProtobufTwist3d::ProtobufTwist3d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufTwist3d)
}
ProtobufTwist3d::ProtobufTwist3d(
    ::google::protobuf::Arena* arena, const ProtobufTwist3d& from)
    : ProtobufTwist3d(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ProtobufTwist3d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufTwist3d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, dx_),
           0,
           offsetof(Impl_, rz_) -
               offsetof(Impl_, dx_) +
               sizeof(Impl_::rz_));
}
ProtobufTwist3d::~ProtobufTwist3d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufTwist3d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufTwist3d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufTwist3d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufTwist3d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufTwist3d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufTwist3d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufTwist3d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufTwist3d>(), &ProtobufTwist3d::ByteSizeLong,
                &ProtobufTwist3d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_._cached_size_),
            false,
        },
        &ProtobufTwist3d::kDescriptorMethods,
        &descriptor_table_geometry3d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufTwist3d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2> ProtobufTwist3d::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTwist3d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double dx = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.dx_)}},
    // double dy = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.dy_)}},
    // double dz = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.dz_)}},
    // double rx = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.rx_)}},
    // double ry = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.ry_)}},
    // double rz = 6;
    {::_pbi::TcParser::FastF64S1,
     {49, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.rz_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // double dx = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.dx_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double dy = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.dy_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double dz = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.dz_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double rx = 4;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.rx_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double ry = 5;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.ry_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double rz = 6;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.rz_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ProtobufTwist3d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufTwist3d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dx_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.rz_) -
      reinterpret_cast<char*>(&_impl_.dx_)) + sizeof(_impl_.rz_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufTwist3d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufTwist3d& this_ = static_cast<const ProtobufTwist3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufTwist3d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufTwist3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufTwist3d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double dx = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_dx()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_dx(), target);
          }

          // double dy = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_dy()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_dy(), target);
          }

          // double dz = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_dz()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_dz(), target);
          }

          // double rx = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_rx()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_rx(), target);
          }

          // double ry = 5;
          if (::absl::bit_cast<::uint64_t>(this_._internal_ry()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                5, this_._internal_ry(), target);
          }

          // double rz = 6;
          if (::absl::bit_cast<::uint64_t>(this_._internal_rz()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                6, this_._internal_rz(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufTwist3d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufTwist3d::ByteSizeLong(const MessageLite& base) {
          const ProtobufTwist3d& this_ = static_cast<const ProtobufTwist3d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufTwist3d::ByteSizeLong() const {
          const ProtobufTwist3d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufTwist3d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double dx = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_dx()) != 0) {
              total_size += 9;
            }
            // double dy = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_dy()) != 0) {
              total_size += 9;
            }
            // double dz = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_dz()) != 0) {
              total_size += 9;
            }
            // double rx = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_rx()) != 0) {
              total_size += 9;
            }
            // double ry = 5;
            if (::absl::bit_cast<::uint64_t>(this_._internal_ry()) != 0) {
              total_size += 9;
            }
            // double rz = 6;
            if (::absl::bit_cast<::uint64_t>(this_._internal_rz()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufTwist3d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufTwist3d*>(&to_msg);
  auto& from = static_cast<const ProtobufTwist3d&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufTwist3d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_dx()) != 0) {
    _this->_impl_.dx_ = from._impl_.dx_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_dy()) != 0) {
    _this->_impl_.dy_ = from._impl_.dy_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_dz()) != 0) {
    _this->_impl_.dz_ = from._impl_.dz_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_rx()) != 0) {
    _this->_impl_.rx_ = from._impl_.rx_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_ry()) != 0) {
    _this->_impl_.ry_ = from._impl_.ry_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_rz()) != 0) {
    _this->_impl_.rz_ = from._impl_.rz_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufTwist3d::CopyFrom(const ProtobufTwist3d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufTwist3d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufTwist3d::InternalSwap(ProtobufTwist3d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.rz_)
      + sizeof(ProtobufTwist3d::_impl_.rz_)
      - PROTOBUF_FIELD_OFFSET(ProtobufTwist3d, _impl_.dx_)>(
          reinterpret_cast<char*>(&_impl_.dx_),
          reinterpret_cast<char*>(&other->_impl_.dx_));
}

::google::protobuf::Metadata ProtobufTwist3d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace wpi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_geometry3d_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
