// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: geometry2d.proto
// Protobuf C++ Version: 5.28.3

#include "geometry2d.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace wpi {
namespace proto {

inline constexpr ProtobufTwist2d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dx_{0},
        dy_{0},
        dtheta_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufTwist2d::ProtobufTwist2d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufTwist2dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufTwist2dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufTwist2dDefaultTypeInternal() {}
  union {
    ProtobufTwist2d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufTwist2dDefaultTypeInternal _ProtobufTwist2d_default_instance_;

inline constexpr ProtobufTranslation2d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufTranslation2d::ProtobufTranslation2d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufTranslation2dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufTranslation2dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufTranslation2dDefaultTypeInternal() {}
  union {
    ProtobufTranslation2d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufTranslation2dDefaultTypeInternal _ProtobufTranslation2d_default_instance_;

inline constexpr ProtobufRotation2d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufRotation2d::ProtobufRotation2d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufRotation2dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufRotation2dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufRotation2dDefaultTypeInternal() {}
  union {
    ProtobufRotation2d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufRotation2dDefaultTypeInternal _ProtobufRotation2d_default_instance_;

inline constexpr ProtobufTransform2d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        translation_{nullptr},
        rotation_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufTransform2d::ProtobufTransform2d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufTransform2dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufTransform2dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufTransform2dDefaultTypeInternal() {}
  union {
    ProtobufTransform2d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufTransform2dDefaultTypeInternal _ProtobufTransform2d_default_instance_;

inline constexpr ProtobufPose2d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        translation_{nullptr},
        rotation_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufPose2d::ProtobufPose2d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufPose2dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufPose2dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufPose2dDefaultTypeInternal() {}
  union {
    ProtobufPose2d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufPose2dDefaultTypeInternal _ProtobufPose2d_default_instance_;

inline constexpr ProtobufRectangle2d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        center_{nullptr},
        xwidth_{0},
        ywidth_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufRectangle2d::ProtobufRectangle2d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufRectangle2dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufRectangle2dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufRectangle2dDefaultTypeInternal() {}
  union {
    ProtobufRectangle2d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufRectangle2dDefaultTypeInternal _ProtobufRectangle2d_default_instance_;

inline constexpr ProtobufEllipse2d::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        center_{nullptr},
        xsemiaxis_{0},
        ysemiaxis_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtobufEllipse2d::ProtobufEllipse2d(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtobufEllipse2dDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufEllipse2dDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufEllipse2dDefaultTypeInternal() {}
  union {
    ProtobufEllipse2d _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufEllipse2dDefaultTypeInternal _ProtobufEllipse2d_default_instance_;
}  // namespace proto
}  // namespace wpi
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_geometry2d_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_geometry2d_2eproto = nullptr;
const ::uint32_t
    TableStruct_geometry2d_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTranslation2d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTranslation2d, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTranslation2d, _impl_.y_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRotation2d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRotation2d, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufPose2d, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufPose2d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufPose2d, _impl_.translation_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufPose2d, _impl_.rotation_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTransform2d, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTransform2d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTransform2d, _impl_.translation_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTransform2d, _impl_.rotation_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist2d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist2d, _impl_.dx_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist2d, _impl_.dy_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufTwist2d, _impl_.dtheta_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRectangle2d, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRectangle2d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRectangle2d, _impl_.center_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRectangle2d, _impl_.xwidth_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufRectangle2d, _impl_.ywidth_),
        0,
        ~0u,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufEllipse2d, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufEllipse2d, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufEllipse2d, _impl_.center_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufEllipse2d, _impl_.xsemiaxis_),
        PROTOBUF_FIELD_OFFSET(::wpi::proto::ProtobufEllipse2d, _impl_.ysemiaxis_),
        0,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::wpi::proto::ProtobufTranslation2d)},
        {10, -1, -1, sizeof(::wpi::proto::ProtobufRotation2d)},
        {19, 29, -1, sizeof(::wpi::proto::ProtobufPose2d)},
        {31, 41, -1, sizeof(::wpi::proto::ProtobufTransform2d)},
        {43, -1, -1, sizeof(::wpi::proto::ProtobufTwist2d)},
        {54, 65, -1, sizeof(::wpi::proto::ProtobufRectangle2d)},
        {68, 79, -1, sizeof(::wpi::proto::ProtobufEllipse2d)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::wpi::proto::_ProtobufTranslation2d_default_instance_._instance,
    &::wpi::proto::_ProtobufRotation2d_default_instance_._instance,
    &::wpi::proto::_ProtobufPose2d_default_instance_._instance,
    &::wpi::proto::_ProtobufTransform2d_default_instance_._instance,
    &::wpi::proto::_ProtobufTwist2d_default_instance_._instance,
    &::wpi::proto::_ProtobufRectangle2d_default_instance_._instance,
    &::wpi::proto::_ProtobufEllipse2d_default_instance_._instance,
};
const char descriptor_table_protodef_geometry2d_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020geometry2d.proto\022\twpi.proto\"-\n\025Protobu"
    "fTranslation2d\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"#\n\022"
    "ProtobufRotation2d\022\r\n\005value\030\001 \001(\001\"x\n\016Pro"
    "tobufPose2d\0225\n\013translation\030\001 \001(\0132 .wpi.p"
    "roto.ProtobufTranslation2d\022/\n\010rotation\030\002"
    " \001(\0132\035.wpi.proto.ProtobufRotation2d\"}\n\023P"
    "rotobufTransform2d\0225\n\013translation\030\001 \001(\0132"
    " .wpi.proto.ProtobufTranslation2d\022/\n\010rot"
    "ation\030\002 \001(\0132\035.wpi.proto.ProtobufRotation"
    "2d\"9\n\017ProtobufTwist2d\022\n\n\002dx\030\001 \001(\001\022\n\n\002dy\030"
    "\002 \001(\001\022\016\n\006dtheta\030\003 \001(\001\"`\n\023ProtobufRectang"
    "le2d\022)\n\006center\030\001 \001(\0132\031.wpi.proto.Protobu"
    "fPose2d\022\016\n\006xWidth\030\002 \001(\001\022\016\n\006yWidth\030\003 \001(\001\""
    "d\n\021ProtobufEllipse2d\022)\n\006center\030\001 \001(\0132\031.w"
    "pi.proto.ProtobufPose2d\022\021\n\txSemiAxis\030\002 \001"
    "(\001\022\021\n\tySemiAxis\030\003 \001(\001B\032\n\030edu.wpi.first.m"
    "ath.protob\006proto3"
};
static ::absl::once_flag descriptor_table_geometry2d_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_geometry2d_2eproto = {
    false,
    false,
    657,
    descriptor_table_protodef_geometry2d_2eproto,
    "geometry2d.proto",
    &descriptor_table_geometry2d_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_geometry2d_2eproto::offsets,
    file_level_enum_descriptors_geometry2d_2eproto,
    file_level_service_descriptors_geometry2d_2eproto,
};
namespace wpi {
namespace proto {
// ===================================================================

class ProtobufTranslation2d::_Internal {
 public:
};

ProtobufTranslation2d::ProtobufTranslation2d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufTranslation2d)
}
ProtobufTranslation2d::ProtobufTranslation2d(
    ::google::protobuf::Arena* arena, const ProtobufTranslation2d& from)
    : ProtobufTranslation2d(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ProtobufTranslation2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufTranslation2d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, y_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::y_));
}
ProtobufTranslation2d::~ProtobufTranslation2d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufTranslation2d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufTranslation2d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufTranslation2d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufTranslation2d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufTranslation2d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufTranslation2d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufTranslation2d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufTranslation2d>(), &ProtobufTranslation2d::ByteSizeLong,
                &ProtobufTranslation2d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufTranslation2d, _impl_._cached_size_),
            false,
        },
        &ProtobufTranslation2d::kDescriptorMethods,
        &descriptor_table_geometry2d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufTranslation2d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ProtobufTranslation2d::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTranslation2d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double y = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTranslation2d, _impl_.y_)}},
    // double x = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTranslation2d, _impl_.x_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double x = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufTranslation2d, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double y = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufTranslation2d, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ProtobufTranslation2d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufTranslation2d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.y_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.y_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufTranslation2d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufTranslation2d& this_ = static_cast<const ProtobufTranslation2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufTranslation2d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufTranslation2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufTranslation2d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double x = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_x(), target);
          }

          // double y = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_y(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufTranslation2d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufTranslation2d::ByteSizeLong(const MessageLite& base) {
          const ProtobufTranslation2d& this_ = static_cast<const ProtobufTranslation2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufTranslation2d::ByteSizeLong() const {
          const ProtobufTranslation2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufTranslation2d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double x = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_x()) != 0) {
              total_size += 9;
            }
            // double y = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_y()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufTranslation2d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufTranslation2d*>(&to_msg);
  auto& from = static_cast<const ProtobufTranslation2d&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufTranslation2d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufTranslation2d::CopyFrom(const ProtobufTranslation2d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufTranslation2d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufTranslation2d::InternalSwap(ProtobufTranslation2d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufTranslation2d, _impl_.y_)
      + sizeof(ProtobufTranslation2d::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(ProtobufTranslation2d, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata ProtobufTranslation2d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufRotation2d::_Internal {
 public:
};

ProtobufRotation2d::ProtobufRotation2d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufRotation2d)
}
ProtobufRotation2d::ProtobufRotation2d(
    ::google::protobuf::Arena* arena, const ProtobufRotation2d& from)
    : ProtobufRotation2d(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ProtobufRotation2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufRotation2d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
ProtobufRotation2d::~ProtobufRotation2d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufRotation2d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufRotation2d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufRotation2d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufRotation2d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufRotation2d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufRotation2d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufRotation2d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufRotation2d>(), &ProtobufRotation2d::ByteSizeLong,
                &ProtobufRotation2d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufRotation2d, _impl_._cached_size_),
            false,
        },
        &ProtobufRotation2d::kDescriptorMethods,
        &descriptor_table_geometry2d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufRotation2d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ProtobufRotation2d::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufRotation2d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double value = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufRotation2d, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double value = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufRotation2d, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ProtobufRotation2d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufRotation2d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufRotation2d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufRotation2d& this_ = static_cast<const ProtobufRotation2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufRotation2d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufRotation2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufRotation2d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double value = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_value()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_value(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufRotation2d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufRotation2d::ByteSizeLong(const MessageLite& base) {
          const ProtobufRotation2d& this_ = static_cast<const ProtobufRotation2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufRotation2d::ByteSizeLong() const {
          const ProtobufRotation2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufRotation2d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // double value = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_value()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufRotation2d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufRotation2d*>(&to_msg);
  auto& from = static_cast<const ProtobufRotation2d&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufRotation2d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_value()) != 0) {
    _this->_impl_.value_ = from._impl_.value_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufRotation2d::CopyFrom(const ProtobufRotation2d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufRotation2d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufRotation2d::InternalSwap(ProtobufRotation2d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata ProtobufRotation2d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufPose2d::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufPose2d>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_._has_bits_);
};

ProtobufPose2d::ProtobufPose2d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufPose2d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufPose2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::wpi::proto::ProtobufPose2d& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufPose2d::ProtobufPose2d(
    ::google::protobuf::Arena* arena,
    const ProtobufPose2d& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufPose2d* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.translation_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufTranslation2d>(
                              arena, *from._impl_.translation_)
                        : nullptr;
  _impl_.rotation_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufRotation2d>(
                              arena, *from._impl_.rotation_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:wpi.proto.ProtobufPose2d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufPose2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufPose2d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, translation_),
           0,
           offsetof(Impl_, rotation_) -
               offsetof(Impl_, translation_) +
               sizeof(Impl_::rotation_));
}
ProtobufPose2d::~ProtobufPose2d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufPose2d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufPose2d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.translation_;
  delete _impl_.rotation_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufPose2d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufPose2d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufPose2d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufPose2d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufPose2d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufPose2d>(), &ProtobufPose2d::ByteSizeLong,
                &ProtobufPose2d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_._cached_size_),
            false,
        },
        &ProtobufPose2d::kDescriptorMethods,
        &descriptor_table_geometry2d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufPose2d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> ProtobufPose2d::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufPose2d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .wpi.proto.ProtobufRotation2d rotation = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_.rotation_)}},
    // .wpi.proto.ProtobufTranslation2d translation = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_.translation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .wpi.proto.ProtobufTranslation2d translation = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_.translation_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .wpi.proto.ProtobufRotation2d rotation = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_.rotation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTranslation2d>()},
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufRotation2d>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufPose2d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufPose2d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.translation_ != nullptr);
      _impl_.translation_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.rotation_ != nullptr);
      _impl_.rotation_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufPose2d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufPose2d& this_ = static_cast<const ProtobufPose2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufPose2d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufPose2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufPose2d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufTranslation2d translation = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.translation_, this_._impl_.translation_->GetCachedSize(), target,
                stream);
          }

          // .wpi.proto.ProtobufRotation2d rotation = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.rotation_, this_._impl_.rotation_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufPose2d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufPose2d::ByteSizeLong(const MessageLite& base) {
          const ProtobufPose2d& this_ = static_cast<const ProtobufPose2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufPose2d::ByteSizeLong() const {
          const ProtobufPose2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufPose2d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .wpi.proto.ProtobufTranslation2d translation = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.translation_);
            }
            // .wpi.proto.ProtobufRotation2d rotation = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rotation_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufPose2d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufPose2d*>(&to_msg);
  auto& from = static_cast<const ProtobufPose2d&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufPose2d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.translation_ != nullptr);
      if (_this->_impl_.translation_ == nullptr) {
        _this->_impl_.translation_ =
            ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufTranslation2d>(arena, *from._impl_.translation_);
      } else {
        _this->_impl_.translation_->MergeFrom(*from._impl_.translation_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.rotation_ != nullptr);
      if (_this->_impl_.rotation_ == nullptr) {
        _this->_impl_.rotation_ =
            ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufRotation2d>(arena, *from._impl_.rotation_);
      } else {
        _this->_impl_.rotation_->MergeFrom(*from._impl_.rotation_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufPose2d::CopyFrom(const ProtobufPose2d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufPose2d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufPose2d::InternalSwap(ProtobufPose2d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_.rotation_)
      + sizeof(ProtobufPose2d::_impl_.rotation_)
      - PROTOBUF_FIELD_OFFSET(ProtobufPose2d, _impl_.translation_)>(
          reinterpret_cast<char*>(&_impl_.translation_),
          reinterpret_cast<char*>(&other->_impl_.translation_));
}

::google::protobuf::Metadata ProtobufPose2d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufTransform2d::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufTransform2d>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_._has_bits_);
};

ProtobufTransform2d::ProtobufTransform2d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufTransform2d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufTransform2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::wpi::proto::ProtobufTransform2d& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufTransform2d::ProtobufTransform2d(
    ::google::protobuf::Arena* arena,
    const ProtobufTransform2d& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufTransform2d* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.translation_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufTranslation2d>(
                              arena, *from._impl_.translation_)
                        : nullptr;
  _impl_.rotation_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufRotation2d>(
                              arena, *from._impl_.rotation_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:wpi.proto.ProtobufTransform2d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufTransform2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufTransform2d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, translation_),
           0,
           offsetof(Impl_, rotation_) -
               offsetof(Impl_, translation_) +
               sizeof(Impl_::rotation_));
}
ProtobufTransform2d::~ProtobufTransform2d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufTransform2d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufTransform2d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.translation_;
  delete _impl_.rotation_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufTransform2d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufTransform2d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufTransform2d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufTransform2d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufTransform2d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufTransform2d>(), &ProtobufTransform2d::ByteSizeLong,
                &ProtobufTransform2d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_._cached_size_),
            false,
        },
        &ProtobufTransform2d::kDescriptorMethods,
        &descriptor_table_geometry2d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufTransform2d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> ProtobufTransform2d::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTransform2d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .wpi.proto.ProtobufRotation2d rotation = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_.rotation_)}},
    // .wpi.proto.ProtobufTranslation2d translation = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_.translation_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .wpi.proto.ProtobufTranslation2d translation = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_.translation_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .wpi.proto.ProtobufRotation2d rotation = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_.rotation_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTranslation2d>()},
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufRotation2d>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufTransform2d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufTransform2d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.translation_ != nullptr);
      _impl_.translation_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.rotation_ != nullptr);
      _impl_.rotation_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufTransform2d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufTransform2d& this_ = static_cast<const ProtobufTransform2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufTransform2d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufTransform2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufTransform2d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufTranslation2d translation = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.translation_, this_._impl_.translation_->GetCachedSize(), target,
                stream);
          }

          // .wpi.proto.ProtobufRotation2d rotation = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.rotation_, this_._impl_.rotation_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufTransform2d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufTransform2d::ByteSizeLong(const MessageLite& base) {
          const ProtobufTransform2d& this_ = static_cast<const ProtobufTransform2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufTransform2d::ByteSizeLong() const {
          const ProtobufTransform2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufTransform2d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .wpi.proto.ProtobufTranslation2d translation = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.translation_);
            }
            // .wpi.proto.ProtobufRotation2d rotation = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.rotation_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufTransform2d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufTransform2d*>(&to_msg);
  auto& from = static_cast<const ProtobufTransform2d&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufTransform2d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.translation_ != nullptr);
      if (_this->_impl_.translation_ == nullptr) {
        _this->_impl_.translation_ =
            ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufTranslation2d>(arena, *from._impl_.translation_);
      } else {
        _this->_impl_.translation_->MergeFrom(*from._impl_.translation_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.rotation_ != nullptr);
      if (_this->_impl_.rotation_ == nullptr) {
        _this->_impl_.rotation_ =
            ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufRotation2d>(arena, *from._impl_.rotation_);
      } else {
        _this->_impl_.rotation_->MergeFrom(*from._impl_.rotation_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufTransform2d::CopyFrom(const ProtobufTransform2d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufTransform2d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufTransform2d::InternalSwap(ProtobufTransform2d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_.rotation_)
      + sizeof(ProtobufTransform2d::_impl_.rotation_)
      - PROTOBUF_FIELD_OFFSET(ProtobufTransform2d, _impl_.translation_)>(
          reinterpret_cast<char*>(&_impl_.translation_),
          reinterpret_cast<char*>(&other->_impl_.translation_));
}

::google::protobuf::Metadata ProtobufTransform2d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufTwist2d::_Internal {
 public:
};

ProtobufTwist2d::ProtobufTwist2d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufTwist2d)
}
ProtobufTwist2d::ProtobufTwist2d(
    ::google::protobuf::Arena* arena, const ProtobufTwist2d& from)
    : ProtobufTwist2d(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ProtobufTwist2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufTwist2d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, dx_),
           0,
           offsetof(Impl_, dtheta_) -
               offsetof(Impl_, dx_) +
               sizeof(Impl_::dtheta_));
}
ProtobufTwist2d::~ProtobufTwist2d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufTwist2d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufTwist2d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufTwist2d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufTwist2d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufTwist2d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufTwist2d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufTwist2d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufTwist2d>(), &ProtobufTwist2d::ByteSizeLong,
                &ProtobufTwist2d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_._cached_size_),
            false,
        },
        &ProtobufTwist2d::kDescriptorMethods,
        &descriptor_table_geometry2d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufTwist2d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ProtobufTwist2d::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufTwist2d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double dx = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_.dx_)}},
    // double dy = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_.dy_)}},
    // double dtheta = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_.dtheta_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double dx = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_.dx_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double dy = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_.dy_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double dtheta = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_.dtheta_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ProtobufTwist2d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufTwist2d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dx_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.dtheta_) -
      reinterpret_cast<char*>(&_impl_.dx_)) + sizeof(_impl_.dtheta_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufTwist2d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufTwist2d& this_ = static_cast<const ProtobufTwist2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufTwist2d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufTwist2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufTwist2d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double dx = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_dx()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_dx(), target);
          }

          // double dy = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_dy()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_dy(), target);
          }

          // double dtheta = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_dtheta()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_dtheta(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufTwist2d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufTwist2d::ByteSizeLong(const MessageLite& base) {
          const ProtobufTwist2d& this_ = static_cast<const ProtobufTwist2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufTwist2d::ByteSizeLong() const {
          const ProtobufTwist2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufTwist2d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double dx = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_dx()) != 0) {
              total_size += 9;
            }
            // double dy = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_dy()) != 0) {
              total_size += 9;
            }
            // double dtheta = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_dtheta()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufTwist2d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufTwist2d*>(&to_msg);
  auto& from = static_cast<const ProtobufTwist2d&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufTwist2d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_dx()) != 0) {
    _this->_impl_.dx_ = from._impl_.dx_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_dy()) != 0) {
    _this->_impl_.dy_ = from._impl_.dy_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_dtheta()) != 0) {
    _this->_impl_.dtheta_ = from._impl_.dtheta_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufTwist2d::CopyFrom(const ProtobufTwist2d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufTwist2d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufTwist2d::InternalSwap(ProtobufTwist2d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_.dtheta_)
      + sizeof(ProtobufTwist2d::_impl_.dtheta_)
      - PROTOBUF_FIELD_OFFSET(ProtobufTwist2d, _impl_.dx_)>(
          reinterpret_cast<char*>(&_impl_.dx_),
          reinterpret_cast<char*>(&other->_impl_.dx_));
}

::google::protobuf::Metadata ProtobufTwist2d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufRectangle2d::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufRectangle2d>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_._has_bits_);
};

ProtobufRectangle2d::ProtobufRectangle2d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufRectangle2d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufRectangle2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::wpi::proto::ProtobufRectangle2d& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufRectangle2d::ProtobufRectangle2d(
    ::google::protobuf::Arena* arena,
    const ProtobufRectangle2d& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufRectangle2d* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.center_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufPose2d>(
                              arena, *from._impl_.center_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, xwidth_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, xwidth_),
           offsetof(Impl_, ywidth_) -
               offsetof(Impl_, xwidth_) +
               sizeof(Impl_::ywidth_));

  // @@protoc_insertion_point(copy_constructor:wpi.proto.ProtobufRectangle2d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufRectangle2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufRectangle2d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, center_),
           0,
           offsetof(Impl_, ywidth_) -
               offsetof(Impl_, center_) +
               sizeof(Impl_::ywidth_));
}
ProtobufRectangle2d::~ProtobufRectangle2d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufRectangle2d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufRectangle2d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.center_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufRectangle2d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufRectangle2d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufRectangle2d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufRectangle2d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufRectangle2d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufRectangle2d>(), &ProtobufRectangle2d::ByteSizeLong,
                &ProtobufRectangle2d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_._cached_size_),
            false,
        },
        &ProtobufRectangle2d::kDescriptorMethods,
        &descriptor_table_geometry2d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufRectangle2d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> ProtobufRectangle2d::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufRectangle2d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .wpi.proto.ProtobufPose2d center = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_.center_)}},
    // double xWidth = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_.xwidth_)}},
    // double yWidth = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_.ywidth_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .wpi.proto.ProtobufPose2d center = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_.center_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // double xWidth = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_.xwidth_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double yWidth = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_.ywidth_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufPose2d>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufRectangle2d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufRectangle2d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.center_ != nullptr);
    _impl_.center_->Clear();
  }
  ::memset(&_impl_.xwidth_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.ywidth_) -
      reinterpret_cast<char*>(&_impl_.xwidth_)) + sizeof(_impl_.ywidth_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufRectangle2d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufRectangle2d& this_ = static_cast<const ProtobufRectangle2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufRectangle2d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufRectangle2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufRectangle2d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufPose2d center = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.center_, this_._impl_.center_->GetCachedSize(), target,
                stream);
          }

          // double xWidth = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_xwidth()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_xwidth(), target);
          }

          // double yWidth = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_ywidth()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_ywidth(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufRectangle2d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufRectangle2d::ByteSizeLong(const MessageLite& base) {
          const ProtobufRectangle2d& this_ = static_cast<const ProtobufRectangle2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufRectangle2d::ByteSizeLong() const {
          const ProtobufRectangle2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufRectangle2d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .wpi.proto.ProtobufPose2d center = 1;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.center_);
            }
          }
           {
            // double xWidth = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_xwidth()) != 0) {
              total_size += 9;
            }
            // double yWidth = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_ywidth()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufRectangle2d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufRectangle2d*>(&to_msg);
  auto& from = static_cast<const ProtobufRectangle2d&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufRectangle2d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.center_ != nullptr);
    if (_this->_impl_.center_ == nullptr) {
      _this->_impl_.center_ =
          ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufPose2d>(arena, *from._impl_.center_);
    } else {
      _this->_impl_.center_->MergeFrom(*from._impl_.center_);
    }
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_xwidth()) != 0) {
    _this->_impl_.xwidth_ = from._impl_.xwidth_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_ywidth()) != 0) {
    _this->_impl_.ywidth_ = from._impl_.ywidth_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufRectangle2d::CopyFrom(const ProtobufRectangle2d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufRectangle2d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufRectangle2d::InternalSwap(ProtobufRectangle2d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_.ywidth_)
      + sizeof(ProtobufRectangle2d::_impl_.ywidth_)
      - PROTOBUF_FIELD_OFFSET(ProtobufRectangle2d, _impl_.center_)>(
          reinterpret_cast<char*>(&_impl_.center_),
          reinterpret_cast<char*>(&other->_impl_.center_));
}

::google::protobuf::Metadata ProtobufRectangle2d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProtobufEllipse2d::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProtobufEllipse2d>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_._has_bits_);
};

ProtobufEllipse2d::ProtobufEllipse2d(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:wpi.proto.ProtobufEllipse2d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufEllipse2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::wpi::proto::ProtobufEllipse2d& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ProtobufEllipse2d::ProtobufEllipse2d(
    ::google::protobuf::Arena* arena,
    const ProtobufEllipse2d& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtobufEllipse2d* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.center_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufPose2d>(
                              arena, *from._impl_.center_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, xsemiaxis_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, xsemiaxis_),
           offsetof(Impl_, ysemiaxis_) -
               offsetof(Impl_, xsemiaxis_) +
               sizeof(Impl_::ysemiaxis_));

  // @@protoc_insertion_point(copy_constructor:wpi.proto.ProtobufEllipse2d)
}
inline PROTOBUF_NDEBUG_INLINE ProtobufEllipse2d::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ProtobufEllipse2d::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, center_),
           0,
           offsetof(Impl_, ysemiaxis_) -
               offsetof(Impl_, center_) +
               sizeof(Impl_::ysemiaxis_));
}
ProtobufEllipse2d::~ProtobufEllipse2d() {
  // @@protoc_insertion_point(destructor:wpi.proto.ProtobufEllipse2d)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProtobufEllipse2d::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.center_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ProtobufEllipse2d::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ProtobufEllipse2d_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ProtobufEllipse2d::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<ProtobufEllipse2d>(),
            ::google::protobuf::Message::GetNewImpl<ProtobufEllipse2d>(),
            ::google::protobuf::Message::GetClearImpl<ProtobufEllipse2d>(), &ProtobufEllipse2d::ByteSizeLong,
                &ProtobufEllipse2d::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_._cached_size_),
            false,
        },
        &ProtobufEllipse2d::kDescriptorMethods,
        &descriptor_table_geometry2d_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ProtobufEllipse2d::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> ProtobufEllipse2d::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::wpi::proto::ProtobufEllipse2d>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .wpi.proto.ProtobufPose2d center = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_.center_)}},
    // double xSemiAxis = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_.xsemiaxis_)}},
    // double ySemiAxis = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_.ysemiaxis_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .wpi.proto.ProtobufPose2d center = 1;
    {PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_.center_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // double xSemiAxis = 2;
    {PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_.xsemiaxis_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double ySemiAxis = 3;
    {PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_.ysemiaxis_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }}, {{
    {::_pbi::TcParser::GetTable<::wpi::proto::ProtobufPose2d>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ProtobufEllipse2d::Clear() {
// @@protoc_insertion_point(message_clear_start:wpi.proto.ProtobufEllipse2d)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.center_ != nullptr);
    _impl_.center_->Clear();
  }
  ::memset(&_impl_.xsemiaxis_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.ysemiaxis_) -
      reinterpret_cast<char*>(&_impl_.xsemiaxis_)) + sizeof(_impl_.ysemiaxis_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtobufEllipse2d::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtobufEllipse2d& this_ = static_cast<const ProtobufEllipse2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtobufEllipse2d::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtobufEllipse2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:wpi.proto.ProtobufEllipse2d)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .wpi.proto.ProtobufPose2d center = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.center_, this_._impl_.center_->GetCachedSize(), target,
                stream);
          }

          // double xSemiAxis = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_xsemiaxis()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_xsemiaxis(), target);
          }

          // double ySemiAxis = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_ysemiaxis()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_ysemiaxis(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:wpi.proto.ProtobufEllipse2d)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtobufEllipse2d::ByteSizeLong(const MessageLite& base) {
          const ProtobufEllipse2d& this_ = static_cast<const ProtobufEllipse2d&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtobufEllipse2d::ByteSizeLong() const {
          const ProtobufEllipse2d& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:wpi.proto.ProtobufEllipse2d)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .wpi.proto.ProtobufPose2d center = 1;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.center_);
            }
          }
           {
            // double xSemiAxis = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_xsemiaxis()) != 0) {
              total_size += 9;
            }
            // double ySemiAxis = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_ysemiaxis()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtobufEllipse2d::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtobufEllipse2d*>(&to_msg);
  auto& from = static_cast<const ProtobufEllipse2d&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:wpi.proto.ProtobufEllipse2d)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.center_ != nullptr);
    if (_this->_impl_.center_ == nullptr) {
      _this->_impl_.center_ =
          ::google::protobuf::Message::CopyConstruct<::wpi::proto::ProtobufPose2d>(arena, *from._impl_.center_);
    } else {
      _this->_impl_.center_->MergeFrom(*from._impl_.center_);
    }
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_xsemiaxis()) != 0) {
    _this->_impl_.xsemiaxis_ = from._impl_.xsemiaxis_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_ysemiaxis()) != 0) {
    _this->_impl_.ysemiaxis_ = from._impl_.ysemiaxis_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufEllipse2d::CopyFrom(const ProtobufEllipse2d& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:wpi.proto.ProtobufEllipse2d)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtobufEllipse2d::InternalSwap(ProtobufEllipse2d* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_.ysemiaxis_)
      + sizeof(ProtobufEllipse2d::_impl_.ysemiaxis_)
      - PROTOBUF_FIELD_OFFSET(ProtobufEllipse2d, _impl_.center_)>(
          reinterpret_cast<char*>(&_impl_.center_),
          reinterpret_cast<char*>(&other->_impl_.center_));
}

::google::protobuf::Metadata ProtobufEllipse2d::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace wpi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_geometry2d_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
