// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commands.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_commands_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_commands_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "geometry3d.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_commands_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_commands_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_commands_2eproto;
namespace questnav {
namespace protos {
namespace commands {
class ProtobufQuestNavCommand;
struct ProtobufQuestNavCommandDefaultTypeInternal;
extern ProtobufQuestNavCommandDefaultTypeInternal _ProtobufQuestNavCommand_default_instance_;
class ProtobufQuestNavCommandResponse;
struct ProtobufQuestNavCommandResponseDefaultTypeInternal;
extern ProtobufQuestNavCommandResponseDefaultTypeInternal _ProtobufQuestNavCommandResponse_default_instance_;
class ProtobufQuestNavPoseResetPayload;
struct ProtobufQuestNavPoseResetPayloadDefaultTypeInternal;
extern ProtobufQuestNavPoseResetPayloadDefaultTypeInternal _ProtobufQuestNavPoseResetPayload_default_instance_;
}  // namespace commands
}  // namespace protos
}  // namespace questnav
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace questnav {
namespace protos {
namespace commands {
enum QuestNavCommandType : int {
  COMMAND_TYPE_UNSPECIFIED = 0,
  POSE_RESET = 1,
  QuestNavCommandType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  QuestNavCommandType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool QuestNavCommandType_IsValid(int value);
extern const uint32_t QuestNavCommandType_internal_data_[];
constexpr QuestNavCommandType QuestNavCommandType_MIN = static_cast<QuestNavCommandType>(0);
constexpr QuestNavCommandType QuestNavCommandType_MAX = static_cast<QuestNavCommandType>(1);
constexpr int QuestNavCommandType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
QuestNavCommandType_descriptor();
template <typename T>
const std::string& QuestNavCommandType_Name(T value) {
  static_assert(std::is_same<T, QuestNavCommandType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to QuestNavCommandType_Name().");
  return QuestNavCommandType_Name(static_cast<QuestNavCommandType>(value));
}
template <>
inline const std::string& QuestNavCommandType_Name(QuestNavCommandType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<QuestNavCommandType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool QuestNavCommandType_Parse(absl::string_view name, QuestNavCommandType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<QuestNavCommandType>(
      QuestNavCommandType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class ProtobufQuestNavCommandResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:questnav.protos.commands.ProtobufQuestNavCommandResponse) */ {
 public:
  inline ProtobufQuestNavCommandResponse() : ProtobufQuestNavCommandResponse(nullptr) {}
  ~ProtobufQuestNavCommandResponse() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufQuestNavCommandResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufQuestNavCommandResponse(const ProtobufQuestNavCommandResponse& from) : ProtobufQuestNavCommandResponse(nullptr, from) {}
  inline ProtobufQuestNavCommandResponse(ProtobufQuestNavCommandResponse&& from) noexcept
      : ProtobufQuestNavCommandResponse(nullptr, std::move(from)) {}
  inline ProtobufQuestNavCommandResponse& operator=(const ProtobufQuestNavCommandResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufQuestNavCommandResponse& operator=(ProtobufQuestNavCommandResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufQuestNavCommandResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufQuestNavCommandResponse* internal_default_instance() {
    return reinterpret_cast<const ProtobufQuestNavCommandResponse*>(
        &_ProtobufQuestNavCommandResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ProtobufQuestNavCommandResponse& a, ProtobufQuestNavCommandResponse& b) { a.Swap(&b); }
  inline void Swap(ProtobufQuestNavCommandResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufQuestNavCommandResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufQuestNavCommandResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufQuestNavCommandResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufQuestNavCommandResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufQuestNavCommandResponse& from) { ProtobufQuestNavCommandResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufQuestNavCommandResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "questnav.protos.commands.ProtobufQuestNavCommandResponse"; }

 protected:
  explicit ProtobufQuestNavCommandResponse(::google::protobuf::Arena* arena);
  ProtobufQuestNavCommandResponse(::google::protobuf::Arena* arena, const ProtobufQuestNavCommandResponse& from);
  ProtobufQuestNavCommandResponse(::google::protobuf::Arena* arena, ProtobufQuestNavCommandResponse&& from) noexcept
      : ProtobufQuestNavCommandResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorMessageFieldNumber = 3,
    kCommandIdFieldNumber = 1,
    kSuccessFieldNumber = 2,
  };
  // string error_message = 3;
  void clear_error_message() ;
  const std::string& error_message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_error_message(Arg_&& arg, Args_... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* value);

  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(
      const std::string& value);
  std::string* _internal_mutable_error_message();

  public:
  // uint32 command_id = 1;
  void clear_command_id() ;
  ::uint32_t command_id() const;
  void set_command_id(::uint32_t value);

  private:
  ::uint32_t _internal_command_id() const;
  void _internal_set_command_id(::uint32_t value);

  public:
  // bool success = 2;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:questnav.protos.commands.ProtobufQuestNavCommandResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      78, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufQuestNavCommandResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufQuestNavCommandResponse& from_msg);
    ::google::protobuf::internal::ArenaStringPtr error_message_;
    ::uint32_t command_id_;
    bool success_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_commands_2eproto;
};
// -------------------------------------------------------------------

class ProtobufQuestNavPoseResetPayload final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:questnav.protos.commands.ProtobufQuestNavPoseResetPayload) */ {
 public:
  inline ProtobufQuestNavPoseResetPayload() : ProtobufQuestNavPoseResetPayload(nullptr) {}
  ~ProtobufQuestNavPoseResetPayload() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufQuestNavPoseResetPayload(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufQuestNavPoseResetPayload(const ProtobufQuestNavPoseResetPayload& from) : ProtobufQuestNavPoseResetPayload(nullptr, from) {}
  inline ProtobufQuestNavPoseResetPayload(ProtobufQuestNavPoseResetPayload&& from) noexcept
      : ProtobufQuestNavPoseResetPayload(nullptr, std::move(from)) {}
  inline ProtobufQuestNavPoseResetPayload& operator=(const ProtobufQuestNavPoseResetPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufQuestNavPoseResetPayload& operator=(ProtobufQuestNavPoseResetPayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufQuestNavPoseResetPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufQuestNavPoseResetPayload* internal_default_instance() {
    return reinterpret_cast<const ProtobufQuestNavPoseResetPayload*>(
        &_ProtobufQuestNavPoseResetPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ProtobufQuestNavPoseResetPayload& a, ProtobufQuestNavPoseResetPayload& b) { a.Swap(&b); }
  inline void Swap(ProtobufQuestNavPoseResetPayload* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufQuestNavPoseResetPayload* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufQuestNavPoseResetPayload* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufQuestNavPoseResetPayload>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufQuestNavPoseResetPayload& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufQuestNavPoseResetPayload& from) { ProtobufQuestNavPoseResetPayload::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufQuestNavPoseResetPayload* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "questnav.protos.commands.ProtobufQuestNavPoseResetPayload"; }

 protected:
  explicit ProtobufQuestNavPoseResetPayload(::google::protobuf::Arena* arena);
  ProtobufQuestNavPoseResetPayload(::google::protobuf::Arena* arena, const ProtobufQuestNavPoseResetPayload& from);
  ProtobufQuestNavPoseResetPayload(::google::protobuf::Arena* arena, ProtobufQuestNavPoseResetPayload&& from) noexcept
      : ProtobufQuestNavPoseResetPayload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTargetPoseFieldNumber = 1,
  };
  // .wpi.proto.ProtobufPose3d target_pose = 1;
  bool has_target_pose() const;
  void clear_target_pose() ;
  const ::wpi::proto::ProtobufPose3d& target_pose() const;
  PROTOBUF_NODISCARD ::wpi::proto::ProtobufPose3d* release_target_pose();
  ::wpi::proto::ProtobufPose3d* mutable_target_pose();
  void set_allocated_target_pose(::wpi::proto::ProtobufPose3d* value);
  void unsafe_arena_set_allocated_target_pose(::wpi::proto::ProtobufPose3d* value);
  ::wpi::proto::ProtobufPose3d* unsafe_arena_release_target_pose();

  private:
  const ::wpi::proto::ProtobufPose3d& _internal_target_pose() const;
  ::wpi::proto::ProtobufPose3d* _internal_mutable_target_pose();

  public:
  // @@protoc_insertion_point(class_scope:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufQuestNavPoseResetPayload_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufQuestNavPoseResetPayload& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::wpi::proto::ProtobufPose3d* target_pose_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_commands_2eproto;
};
// -------------------------------------------------------------------

class ProtobufQuestNavCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:questnav.protos.commands.ProtobufQuestNavCommand) */ {
 public:
  inline ProtobufQuestNavCommand() : ProtobufQuestNavCommand(nullptr) {}
  ~ProtobufQuestNavCommand() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufQuestNavCommand(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufQuestNavCommand(const ProtobufQuestNavCommand& from) : ProtobufQuestNavCommand(nullptr, from) {}
  inline ProtobufQuestNavCommand(ProtobufQuestNavCommand&& from) noexcept
      : ProtobufQuestNavCommand(nullptr, std::move(from)) {}
  inline ProtobufQuestNavCommand& operator=(const ProtobufQuestNavCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufQuestNavCommand& operator=(ProtobufQuestNavCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufQuestNavCommand& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kPoseResetPayload = 10,
    PAYLOAD_NOT_SET = 0,
  };
  static inline const ProtobufQuestNavCommand* internal_default_instance() {
    return reinterpret_cast<const ProtobufQuestNavCommand*>(
        &_ProtobufQuestNavCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ProtobufQuestNavCommand& a, ProtobufQuestNavCommand& b) { a.Swap(&b); }
  inline void Swap(ProtobufQuestNavCommand* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufQuestNavCommand* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufQuestNavCommand* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufQuestNavCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufQuestNavCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufQuestNavCommand& from) { ProtobufQuestNavCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufQuestNavCommand* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "questnav.protos.commands.ProtobufQuestNavCommand"; }

 protected:
  explicit ProtobufQuestNavCommand(::google::protobuf::Arena* arena);
  ProtobufQuestNavCommand(::google::protobuf::Arena* arena, const ProtobufQuestNavCommand& from);
  ProtobufQuestNavCommand(::google::protobuf::Arena* arena, ProtobufQuestNavCommand&& from) noexcept
      : ProtobufQuestNavCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
    kCommandIdFieldNumber = 2,
    kPoseResetPayloadFieldNumber = 10,
  };
  // .questnav.protos.commands.QuestNavCommandType type = 1;
  void clear_type() ;
  ::questnav::protos::commands::QuestNavCommandType type() const;
  void set_type(::questnav::protos::commands::QuestNavCommandType value);

  private:
  ::questnav::protos::commands::QuestNavCommandType _internal_type() const;
  void _internal_set_type(::questnav::protos::commands::QuestNavCommandType value);

  public:
  // uint32 command_id = 2;
  void clear_command_id() ;
  ::uint32_t command_id() const;
  void set_command_id(::uint32_t value);

  private:
  ::uint32_t _internal_command_id() const;
  void _internal_set_command_id(::uint32_t value);

  public:
  // .questnav.protos.commands.ProtobufQuestNavPoseResetPayload pose_reset_payload = 10;
  bool has_pose_reset_payload() const;
  private:
  bool _internal_has_pose_reset_payload() const;

  public:
  void clear_pose_reset_payload() ;
  const ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload& pose_reset_payload() const;
  PROTOBUF_NODISCARD ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* release_pose_reset_payload();
  ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* mutable_pose_reset_payload();
  void set_allocated_pose_reset_payload(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* value);
  void unsafe_arena_set_allocated_pose_reset_payload(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* value);
  ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* unsafe_arena_release_pose_reset_payload();

  private:
  const ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload& _internal_pose_reset_payload() const;
  ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* _internal_mutable_pose_reset_payload();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:questnav.protos.commands.ProtobufQuestNavCommand)
 private:
  class _Internal;
  void set_has_pose_reset_payload();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 3, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufQuestNavCommand_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufQuestNavCommand& from_msg);
    int type_;
    ::uint32_t command_id_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* pose_reset_payload_;
    } payload_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_commands_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ProtobufQuestNavPoseResetPayload

// .wpi.proto.ProtobufPose3d target_pose = 1;
inline bool ProtobufQuestNavPoseResetPayload::has_target_pose() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.target_pose_ != nullptr);
  return value;
}
inline const ::wpi::proto::ProtobufPose3d& ProtobufQuestNavPoseResetPayload::_internal_target_pose() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::wpi::proto::ProtobufPose3d* p = _impl_.target_pose_;
  return p != nullptr ? *p : reinterpret_cast<const ::wpi::proto::ProtobufPose3d&>(::wpi::proto::_ProtobufPose3d_default_instance_);
}
inline const ::wpi::proto::ProtobufPose3d& ProtobufQuestNavPoseResetPayload::target_pose() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:questnav.protos.commands.ProtobufQuestNavPoseResetPayload.target_pose)
  return _internal_target_pose();
}
inline void ProtobufQuestNavPoseResetPayload::unsafe_arena_set_allocated_target_pose(::wpi::proto::ProtobufPose3d* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.target_pose_);
  }
  _impl_.target_pose_ = reinterpret_cast<::wpi::proto::ProtobufPose3d*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:questnav.protos.commands.ProtobufQuestNavPoseResetPayload.target_pose)
}
inline ::wpi::proto::ProtobufPose3d* ProtobufQuestNavPoseResetPayload::release_target_pose() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wpi::proto::ProtobufPose3d* released = _impl_.target_pose_;
  _impl_.target_pose_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::wpi::proto::ProtobufPose3d* ProtobufQuestNavPoseResetPayload::unsafe_arena_release_target_pose() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:questnav.protos.commands.ProtobufQuestNavPoseResetPayload.target_pose)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wpi::proto::ProtobufPose3d* temp = _impl_.target_pose_;
  _impl_.target_pose_ = nullptr;
  return temp;
}
inline ::wpi::proto::ProtobufPose3d* ProtobufQuestNavPoseResetPayload::_internal_mutable_target_pose() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.target_pose_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::wpi::proto::ProtobufPose3d>(GetArena());
    _impl_.target_pose_ = reinterpret_cast<::wpi::proto::ProtobufPose3d*>(p);
  }
  return _impl_.target_pose_;
}
inline ::wpi::proto::ProtobufPose3d* ProtobufQuestNavPoseResetPayload::mutable_target_pose() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::wpi::proto::ProtobufPose3d* _msg = _internal_mutable_target_pose();
  // @@protoc_insertion_point(field_mutable:questnav.protos.commands.ProtobufQuestNavPoseResetPayload.target_pose)
  return _msg;
}
inline void ProtobufQuestNavPoseResetPayload::set_allocated_target_pose(::wpi::proto::ProtobufPose3d* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.target_pose_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.target_pose_ = reinterpret_cast<::wpi::proto::ProtobufPose3d*>(value);
  // @@protoc_insertion_point(field_set_allocated:questnav.protos.commands.ProtobufQuestNavPoseResetPayload.target_pose)
}

// -------------------------------------------------------------------

// ProtobufQuestNavCommand

// .questnav.protos.commands.QuestNavCommandType type = 1;
inline void ProtobufQuestNavCommand::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::questnav::protos::commands::QuestNavCommandType ProtobufQuestNavCommand::type() const {
  // @@protoc_insertion_point(field_get:questnav.protos.commands.ProtobufQuestNavCommand.type)
  return _internal_type();
}
inline void ProtobufQuestNavCommand::set_type(::questnav::protos::commands::QuestNavCommandType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:questnav.protos.commands.ProtobufQuestNavCommand.type)
}
inline ::questnav::protos::commands::QuestNavCommandType ProtobufQuestNavCommand::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::questnav::protos::commands::QuestNavCommandType>(_impl_.type_);
}
inline void ProtobufQuestNavCommand::_internal_set_type(::questnav::protos::commands::QuestNavCommandType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// uint32 command_id = 2;
inline void ProtobufQuestNavCommand::clear_command_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_id_ = 0u;
}
inline ::uint32_t ProtobufQuestNavCommand::command_id() const {
  // @@protoc_insertion_point(field_get:questnav.protos.commands.ProtobufQuestNavCommand.command_id)
  return _internal_command_id();
}
inline void ProtobufQuestNavCommand::set_command_id(::uint32_t value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:questnav.protos.commands.ProtobufQuestNavCommand.command_id)
}
inline ::uint32_t ProtobufQuestNavCommand::_internal_command_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.command_id_;
}
inline void ProtobufQuestNavCommand::_internal_set_command_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_id_ = value;
}

// .questnav.protos.commands.ProtobufQuestNavPoseResetPayload pose_reset_payload = 10;
inline bool ProtobufQuestNavCommand::has_pose_reset_payload() const {
  return payload_case() == kPoseResetPayload;
}
inline bool ProtobufQuestNavCommand::_internal_has_pose_reset_payload() const {
  return payload_case() == kPoseResetPayload;
}
inline void ProtobufQuestNavCommand::set_has_pose_reset_payload() {
  _impl_._oneof_case_[0] = kPoseResetPayload;
}
inline void ProtobufQuestNavCommand::clear_pose_reset_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kPoseResetPayload) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.pose_reset_payload_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.pose_reset_payload_);
    }
    clear_has_payload();
  }
}
inline ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* ProtobufQuestNavCommand::release_pose_reset_payload() {
  // @@protoc_insertion_point(field_release:questnav.protos.commands.ProtobufQuestNavCommand.pose_reset_payload)
  if (payload_case() == kPoseResetPayload) {
    clear_has_payload();
    auto* temp = _impl_.payload_.pose_reset_payload_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.pose_reset_payload_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload& ProtobufQuestNavCommand::_internal_pose_reset_payload() const {
  return payload_case() == kPoseResetPayload ? *_impl_.payload_.pose_reset_payload_ : reinterpret_cast<::questnav::protos::commands::ProtobufQuestNavPoseResetPayload&>(::questnav::protos::commands::_ProtobufQuestNavPoseResetPayload_default_instance_);
}
inline const ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload& ProtobufQuestNavCommand::pose_reset_payload() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:questnav.protos.commands.ProtobufQuestNavCommand.pose_reset_payload)
  return _internal_pose_reset_payload();
}
inline ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* ProtobufQuestNavCommand::unsafe_arena_release_pose_reset_payload() {
  // @@protoc_insertion_point(field_unsafe_arena_release:questnav.protos.commands.ProtobufQuestNavCommand.pose_reset_payload)
  if (payload_case() == kPoseResetPayload) {
    clear_has_payload();
    auto* temp = _impl_.payload_.pose_reset_payload_;
    _impl_.payload_.pose_reset_payload_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ProtobufQuestNavCommand::unsafe_arena_set_allocated_pose_reset_payload(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_pose_reset_payload();
    _impl_.payload_.pose_reset_payload_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:questnav.protos.commands.ProtobufQuestNavCommand.pose_reset_payload)
}
inline ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* ProtobufQuestNavCommand::_internal_mutable_pose_reset_payload() {
  if (payload_case() != kPoseResetPayload) {
    clear_payload();
    set_has_pose_reset_payload();
    _impl_.payload_.pose_reset_payload_ =
        ::google::protobuf::Message::DefaultConstruct<::questnav::protos::commands::ProtobufQuestNavPoseResetPayload>(GetArena());
  }
  return _impl_.payload_.pose_reset_payload_;
}
inline ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* ProtobufQuestNavCommand::mutable_pose_reset_payload() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* _msg = _internal_mutable_pose_reset_payload();
  // @@protoc_insertion_point(field_mutable:questnav.protos.commands.ProtobufQuestNavCommand.pose_reset_payload)
  return _msg;
}

inline bool ProtobufQuestNavCommand::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void ProtobufQuestNavCommand::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline ProtobufQuestNavCommand::PayloadCase ProtobufQuestNavCommand::payload_case() const {
  return ProtobufQuestNavCommand::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ProtobufQuestNavCommandResponse

// uint32 command_id = 1;
inline void ProtobufQuestNavCommandResponse::clear_command_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_id_ = 0u;
}
inline ::uint32_t ProtobufQuestNavCommandResponse::command_id() const {
  // @@protoc_insertion_point(field_get:questnav.protos.commands.ProtobufQuestNavCommandResponse.command_id)
  return _internal_command_id();
}
inline void ProtobufQuestNavCommandResponse::set_command_id(::uint32_t value) {
  _internal_set_command_id(value);
  // @@protoc_insertion_point(field_set:questnav.protos.commands.ProtobufQuestNavCommandResponse.command_id)
}
inline ::uint32_t ProtobufQuestNavCommandResponse::_internal_command_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.command_id_;
}
inline void ProtobufQuestNavCommandResponse::_internal_set_command_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_id_ = value;
}

// bool success = 2;
inline void ProtobufQuestNavCommandResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
}
inline bool ProtobufQuestNavCommandResponse::success() const {
  // @@protoc_insertion_point(field_get:questnav.protos.commands.ProtobufQuestNavCommandResponse.success)
  return _internal_success();
}
inline void ProtobufQuestNavCommandResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:questnav.protos.commands.ProtobufQuestNavCommandResponse.success)
}
inline bool ProtobufQuestNavCommandResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void ProtobufQuestNavCommandResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// string error_message = 3;
inline void ProtobufQuestNavCommandResponse::clear_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& ProtobufQuestNavCommandResponse::error_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:questnav.protos.commands.ProtobufQuestNavCommandResponse.error_message)
  return _internal_error_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ProtobufQuestNavCommandResponse::set_error_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:questnav.protos.commands.ProtobufQuestNavCommandResponse.error_message)
}
inline std::string* ProtobufQuestNavCommandResponse::mutable_error_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:questnav.protos.commands.ProtobufQuestNavCommandResponse.error_message)
  return _s;
}
inline const std::string& ProtobufQuestNavCommandResponse::_internal_error_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_message_.Get();
}
inline void ProtobufQuestNavCommandResponse::_internal_set_error_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(value, GetArena());
}
inline std::string* ProtobufQuestNavCommandResponse::_internal_mutable_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_message_.Mutable( GetArena());
}
inline std::string* ProtobufQuestNavCommandResponse::release_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:questnav.protos.commands.ProtobufQuestNavCommandResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void ProtobufQuestNavCommandResponse::set_allocated_error_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.error_message_.IsDefault()) {
          _impl_.error_message_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:questnav.protos.commands.ProtobufQuestNavCommandResponse.error_message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace commands
}  // namespace protos
}  // namespace questnav


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::questnav::protos::commands::QuestNavCommandType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::questnav::protos::commands::QuestNavCommandType>() {
  return ::questnav::protos::commands::QuestNavCommandType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_commands_2eproto_2epb_2eh
