// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: geometry3d.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_geometry3d_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_geometry3d_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_geometry3d_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_geometry3d_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_geometry3d_2eproto;
namespace wpi {
namespace proto {
class ProtobufPose3d;
struct ProtobufPose3dDefaultTypeInternal;
extern ProtobufPose3dDefaultTypeInternal _ProtobufPose3d_default_instance_;
class ProtobufQuaternion;
struct ProtobufQuaternionDefaultTypeInternal;
extern ProtobufQuaternionDefaultTypeInternal _ProtobufQuaternion_default_instance_;
class ProtobufRotation3d;
struct ProtobufRotation3dDefaultTypeInternal;
extern ProtobufRotation3dDefaultTypeInternal _ProtobufRotation3d_default_instance_;
class ProtobufTransform3d;
struct ProtobufTransform3dDefaultTypeInternal;
extern ProtobufTransform3dDefaultTypeInternal _ProtobufTransform3d_default_instance_;
class ProtobufTranslation3d;
struct ProtobufTranslation3dDefaultTypeInternal;
extern ProtobufTranslation3dDefaultTypeInternal _ProtobufTranslation3d_default_instance_;
class ProtobufTwist3d;
struct ProtobufTwist3dDefaultTypeInternal;
extern ProtobufTwist3dDefaultTypeInternal _ProtobufTwist3d_default_instance_;
}  // namespace proto
}  // namespace wpi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace wpi {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class ProtobufTwist3d final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:wpi.proto.ProtobufTwist3d) */ {
 public:
  inline ProtobufTwist3d() : ProtobufTwist3d(nullptr) {}
  ~ProtobufTwist3d() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufTwist3d(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufTwist3d(const ProtobufTwist3d& from) : ProtobufTwist3d(nullptr, from) {}
  inline ProtobufTwist3d(ProtobufTwist3d&& from) noexcept
      : ProtobufTwist3d(nullptr, std::move(from)) {}
  inline ProtobufTwist3d& operator=(const ProtobufTwist3d& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufTwist3d& operator=(ProtobufTwist3d&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufTwist3d& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufTwist3d* internal_default_instance() {
    return reinterpret_cast<const ProtobufTwist3d*>(
        &_ProtobufTwist3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(ProtobufTwist3d& a, ProtobufTwist3d& b) { a.Swap(&b); }
  inline void Swap(ProtobufTwist3d* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufTwist3d* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufTwist3d* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufTwist3d>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufTwist3d& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufTwist3d& from) { ProtobufTwist3d::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufTwist3d* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "wpi.proto.ProtobufTwist3d"; }

 protected:
  explicit ProtobufTwist3d(::google::protobuf::Arena* arena);
  ProtobufTwist3d(::google::protobuf::Arena* arena, const ProtobufTwist3d& from);
  ProtobufTwist3d(::google::protobuf::Arena* arena, ProtobufTwist3d&& from) noexcept
      : ProtobufTwist3d(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDxFieldNumber = 1,
    kDyFieldNumber = 2,
    kDzFieldNumber = 3,
    kRxFieldNumber = 4,
    kRyFieldNumber = 5,
    kRzFieldNumber = 6,
  };
  // double dx = 1;
  void clear_dx() ;
  double dx() const;
  void set_dx(double value);

  private:
  double _internal_dx() const;
  void _internal_set_dx(double value);

  public:
  // double dy = 2;
  void clear_dy() ;
  double dy() const;
  void set_dy(double value);

  private:
  double _internal_dy() const;
  void _internal_set_dy(double value);

  public:
  // double dz = 3;
  void clear_dz() ;
  double dz() const;
  void set_dz(double value);

  private:
  double _internal_dz() const;
  void _internal_set_dz(double value);

  public:
  // double rx = 4;
  void clear_rx() ;
  double rx() const;
  void set_rx(double value);

  private:
  double _internal_rx() const;
  void _internal_set_rx(double value);

  public:
  // double ry = 5;
  void clear_ry() ;
  double ry() const;
  void set_ry(double value);

  private:
  double _internal_ry() const;
  void _internal_set_ry(double value);

  public:
  // double rz = 6;
  void clear_rz() ;
  double rz() const;
  void set_rz(double value);

  private:
  double _internal_rz() const;
  void _internal_set_rz(double value);

  public:
  // @@protoc_insertion_point(class_scope:wpi.proto.ProtobufTwist3d)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufTwist3d_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufTwist3d& from_msg);
    double dx_;
    double dy_;
    double dz_;
    double rx_;
    double ry_;
    double rz_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geometry3d_2eproto;
};
// -------------------------------------------------------------------

class ProtobufTranslation3d final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:wpi.proto.ProtobufTranslation3d) */ {
 public:
  inline ProtobufTranslation3d() : ProtobufTranslation3d(nullptr) {}
  ~ProtobufTranslation3d() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufTranslation3d(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufTranslation3d(const ProtobufTranslation3d& from) : ProtobufTranslation3d(nullptr, from) {}
  inline ProtobufTranslation3d(ProtobufTranslation3d&& from) noexcept
      : ProtobufTranslation3d(nullptr, std::move(from)) {}
  inline ProtobufTranslation3d& operator=(const ProtobufTranslation3d& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufTranslation3d& operator=(ProtobufTranslation3d&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufTranslation3d& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufTranslation3d* internal_default_instance() {
    return reinterpret_cast<const ProtobufTranslation3d*>(
        &_ProtobufTranslation3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ProtobufTranslation3d& a, ProtobufTranslation3d& b) { a.Swap(&b); }
  inline void Swap(ProtobufTranslation3d* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufTranslation3d* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufTranslation3d* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufTranslation3d>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufTranslation3d& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufTranslation3d& from) { ProtobufTranslation3d::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufTranslation3d* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "wpi.proto.ProtobufTranslation3d"; }

 protected:
  explicit ProtobufTranslation3d(::google::protobuf::Arena* arena);
  ProtobufTranslation3d(::google::protobuf::Arena* arena, const ProtobufTranslation3d& from);
  ProtobufTranslation3d(::google::protobuf::Arena* arena, ProtobufTranslation3d&& from) noexcept
      : ProtobufTranslation3d(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x() ;
  double x() const;
  void set_x(double value);

  private:
  double _internal_x() const;
  void _internal_set_x(double value);

  public:
  // double y = 2;
  void clear_y() ;
  double y() const;
  void set_y(double value);

  private:
  double _internal_y() const;
  void _internal_set_y(double value);

  public:
  // double z = 3;
  void clear_z() ;
  double z() const;
  void set_z(double value);

  private:
  double _internal_z() const;
  void _internal_set_z(double value);

  public:
  // @@protoc_insertion_point(class_scope:wpi.proto.ProtobufTranslation3d)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufTranslation3d_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufTranslation3d& from_msg);
    double x_;
    double y_;
    double z_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geometry3d_2eproto;
};
// -------------------------------------------------------------------

class ProtobufQuaternion final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:wpi.proto.ProtobufQuaternion) */ {
 public:
  inline ProtobufQuaternion() : ProtobufQuaternion(nullptr) {}
  ~ProtobufQuaternion() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufQuaternion(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufQuaternion(const ProtobufQuaternion& from) : ProtobufQuaternion(nullptr, from) {}
  inline ProtobufQuaternion(ProtobufQuaternion&& from) noexcept
      : ProtobufQuaternion(nullptr, std::move(from)) {}
  inline ProtobufQuaternion& operator=(const ProtobufQuaternion& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufQuaternion& operator=(ProtobufQuaternion&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufQuaternion& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufQuaternion* internal_default_instance() {
    return reinterpret_cast<const ProtobufQuaternion*>(
        &_ProtobufQuaternion_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ProtobufQuaternion& a, ProtobufQuaternion& b) { a.Swap(&b); }
  inline void Swap(ProtobufQuaternion* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufQuaternion* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufQuaternion* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufQuaternion>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufQuaternion& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufQuaternion& from) { ProtobufQuaternion::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufQuaternion* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "wpi.proto.ProtobufQuaternion"; }

 protected:
  explicit ProtobufQuaternion(::google::protobuf::Arena* arena);
  ProtobufQuaternion(::google::protobuf::Arena* arena, const ProtobufQuaternion& from);
  ProtobufQuaternion(::google::protobuf::Arena* arena, ProtobufQuaternion&& from) noexcept
      : ProtobufQuaternion(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
  };
  // double w = 1;
  void clear_w() ;
  double w() const;
  void set_w(double value);

  private:
  double _internal_w() const;
  void _internal_set_w(double value);

  public:
  // double x = 2;
  void clear_x() ;
  double x() const;
  void set_x(double value);

  private:
  double _internal_x() const;
  void _internal_set_x(double value);

  public:
  // double y = 3;
  void clear_y() ;
  double y() const;
  void set_y(double value);

  private:
  double _internal_y() const;
  void _internal_set_y(double value);

  public:
  // double z = 4;
  void clear_z() ;
  double z() const;
  void set_z(double value);

  private:
  double _internal_z() const;
  void _internal_set_z(double value);

  public:
  // @@protoc_insertion_point(class_scope:wpi.proto.ProtobufQuaternion)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufQuaternion_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufQuaternion& from_msg);
    double w_;
    double x_;
    double y_;
    double z_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geometry3d_2eproto;
};
// -------------------------------------------------------------------

class ProtobufRotation3d final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:wpi.proto.ProtobufRotation3d) */ {
 public:
  inline ProtobufRotation3d() : ProtobufRotation3d(nullptr) {}
  ~ProtobufRotation3d() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufRotation3d(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufRotation3d(const ProtobufRotation3d& from) : ProtobufRotation3d(nullptr, from) {}
  inline ProtobufRotation3d(ProtobufRotation3d&& from) noexcept
      : ProtobufRotation3d(nullptr, std::move(from)) {}
  inline ProtobufRotation3d& operator=(const ProtobufRotation3d& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufRotation3d& operator=(ProtobufRotation3d&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufRotation3d& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufRotation3d* internal_default_instance() {
    return reinterpret_cast<const ProtobufRotation3d*>(
        &_ProtobufRotation3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ProtobufRotation3d& a, ProtobufRotation3d& b) { a.Swap(&b); }
  inline void Swap(ProtobufRotation3d* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufRotation3d* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufRotation3d* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufRotation3d>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufRotation3d& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufRotation3d& from) { ProtobufRotation3d::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufRotation3d* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "wpi.proto.ProtobufRotation3d"; }

 protected:
  explicit ProtobufRotation3d(::google::protobuf::Arena* arena);
  ProtobufRotation3d(::google::protobuf::Arena* arena, const ProtobufRotation3d& from);
  ProtobufRotation3d(::google::protobuf::Arena* arena, ProtobufRotation3d&& from) noexcept
      : ProtobufRotation3d(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQFieldNumber = 1,
  };
  // .wpi.proto.ProtobufQuaternion q = 1;
  bool has_q() const;
  void clear_q() ;
  const ::wpi::proto::ProtobufQuaternion& q() const;
  PROTOBUF_NODISCARD ::wpi::proto::ProtobufQuaternion* release_q();
  ::wpi::proto::ProtobufQuaternion* mutable_q();
  void set_allocated_q(::wpi::proto::ProtobufQuaternion* value);
  void unsafe_arena_set_allocated_q(::wpi::proto::ProtobufQuaternion* value);
  ::wpi::proto::ProtobufQuaternion* unsafe_arena_release_q();

  private:
  const ::wpi::proto::ProtobufQuaternion& _internal_q() const;
  ::wpi::proto::ProtobufQuaternion* _internal_mutable_q();

  public:
  // @@protoc_insertion_point(class_scope:wpi.proto.ProtobufRotation3d)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufRotation3d_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufRotation3d& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::wpi::proto::ProtobufQuaternion* q_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geometry3d_2eproto;
};
// -------------------------------------------------------------------

class ProtobufTransform3d final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:wpi.proto.ProtobufTransform3d) */ {
 public:
  inline ProtobufTransform3d() : ProtobufTransform3d(nullptr) {}
  ~ProtobufTransform3d() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufTransform3d(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufTransform3d(const ProtobufTransform3d& from) : ProtobufTransform3d(nullptr, from) {}
  inline ProtobufTransform3d(ProtobufTransform3d&& from) noexcept
      : ProtobufTransform3d(nullptr, std::move(from)) {}
  inline ProtobufTransform3d& operator=(const ProtobufTransform3d& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufTransform3d& operator=(ProtobufTransform3d&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufTransform3d& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufTransform3d* internal_default_instance() {
    return reinterpret_cast<const ProtobufTransform3d*>(
        &_ProtobufTransform3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(ProtobufTransform3d& a, ProtobufTransform3d& b) { a.Swap(&b); }
  inline void Swap(ProtobufTransform3d* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufTransform3d* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufTransform3d* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufTransform3d>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufTransform3d& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufTransform3d& from) { ProtobufTransform3d::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufTransform3d* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "wpi.proto.ProtobufTransform3d"; }

 protected:
  explicit ProtobufTransform3d(::google::protobuf::Arena* arena);
  ProtobufTransform3d(::google::protobuf::Arena* arena, const ProtobufTransform3d& from);
  ProtobufTransform3d(::google::protobuf::Arena* arena, ProtobufTransform3d&& from) noexcept
      : ProtobufTransform3d(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
  };
  // .wpi.proto.ProtobufTranslation3d translation = 1;
  bool has_translation() const;
  void clear_translation() ;
  const ::wpi::proto::ProtobufTranslation3d& translation() const;
  PROTOBUF_NODISCARD ::wpi::proto::ProtobufTranslation3d* release_translation();
  ::wpi::proto::ProtobufTranslation3d* mutable_translation();
  void set_allocated_translation(::wpi::proto::ProtobufTranslation3d* value);
  void unsafe_arena_set_allocated_translation(::wpi::proto::ProtobufTranslation3d* value);
  ::wpi::proto::ProtobufTranslation3d* unsafe_arena_release_translation();

  private:
  const ::wpi::proto::ProtobufTranslation3d& _internal_translation() const;
  ::wpi::proto::ProtobufTranslation3d* _internal_mutable_translation();

  public:
  // .wpi.proto.ProtobufRotation3d rotation = 2;
  bool has_rotation() const;
  void clear_rotation() ;
  const ::wpi::proto::ProtobufRotation3d& rotation() const;
  PROTOBUF_NODISCARD ::wpi::proto::ProtobufRotation3d* release_rotation();
  ::wpi::proto::ProtobufRotation3d* mutable_rotation();
  void set_allocated_rotation(::wpi::proto::ProtobufRotation3d* value);
  void unsafe_arena_set_allocated_rotation(::wpi::proto::ProtobufRotation3d* value);
  ::wpi::proto::ProtobufRotation3d* unsafe_arena_release_rotation();

  private:
  const ::wpi::proto::ProtobufRotation3d& _internal_rotation() const;
  ::wpi::proto::ProtobufRotation3d* _internal_mutable_rotation();

  public:
  // @@protoc_insertion_point(class_scope:wpi.proto.ProtobufTransform3d)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufTransform3d_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufTransform3d& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::wpi::proto::ProtobufTranslation3d* translation_;
    ::wpi::proto::ProtobufRotation3d* rotation_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geometry3d_2eproto;
};
// -------------------------------------------------------------------

class ProtobufPose3d final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:wpi.proto.ProtobufPose3d) */ {
 public:
  inline ProtobufPose3d() : ProtobufPose3d(nullptr) {}
  ~ProtobufPose3d() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtobufPose3d(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtobufPose3d(const ProtobufPose3d& from) : ProtobufPose3d(nullptr, from) {}
  inline ProtobufPose3d(ProtobufPose3d&& from) noexcept
      : ProtobufPose3d(nullptr, std::move(from)) {}
  inline ProtobufPose3d& operator=(const ProtobufPose3d& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufPose3d& operator=(ProtobufPose3d&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufPose3d& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufPose3d* internal_default_instance() {
    return reinterpret_cast<const ProtobufPose3d*>(
        &_ProtobufPose3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ProtobufPose3d& a, ProtobufPose3d& b) { a.Swap(&b); }
  inline void Swap(ProtobufPose3d* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufPose3d* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufPose3d* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ProtobufPose3d>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtobufPose3d& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtobufPose3d& from) { ProtobufPose3d::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ProtobufPose3d* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "wpi.proto.ProtobufPose3d"; }

 protected:
  explicit ProtobufPose3d(::google::protobuf::Arena* arena);
  ProtobufPose3d(::google::protobuf::Arena* arena, const ProtobufPose3d& from);
  ProtobufPose3d(::google::protobuf::Arena* arena, ProtobufPose3d&& from) noexcept
      : ProtobufPose3d(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
  };
  // .wpi.proto.ProtobufTranslation3d translation = 1;
  bool has_translation() const;
  void clear_translation() ;
  const ::wpi::proto::ProtobufTranslation3d& translation() const;
  PROTOBUF_NODISCARD ::wpi::proto::ProtobufTranslation3d* release_translation();
  ::wpi::proto::ProtobufTranslation3d* mutable_translation();
  void set_allocated_translation(::wpi::proto::ProtobufTranslation3d* value);
  void unsafe_arena_set_allocated_translation(::wpi::proto::ProtobufTranslation3d* value);
  ::wpi::proto::ProtobufTranslation3d* unsafe_arena_release_translation();

  private:
  const ::wpi::proto::ProtobufTranslation3d& _internal_translation() const;
  ::wpi::proto::ProtobufTranslation3d* _internal_mutable_translation();

  public:
  // .wpi.proto.ProtobufRotation3d rotation = 2;
  bool has_rotation() const;
  void clear_rotation() ;
  const ::wpi::proto::ProtobufRotation3d& rotation() const;
  PROTOBUF_NODISCARD ::wpi::proto::ProtobufRotation3d* release_rotation();
  ::wpi::proto::ProtobufRotation3d* mutable_rotation();
  void set_allocated_rotation(::wpi::proto::ProtobufRotation3d* value);
  void unsafe_arena_set_allocated_rotation(::wpi::proto::ProtobufRotation3d* value);
  ::wpi::proto::ProtobufRotation3d* unsafe_arena_release_rotation();

  private:
  const ::wpi::proto::ProtobufRotation3d& _internal_rotation() const;
  ::wpi::proto::ProtobufRotation3d* _internal_mutable_rotation();

  public:
  // @@protoc_insertion_point(class_scope:wpi.proto.ProtobufPose3d)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ProtobufPose3d_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtobufPose3d& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::wpi::proto::ProtobufTranslation3d* translation_;
    ::wpi::proto::ProtobufRotation3d* rotation_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geometry3d_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ProtobufTranslation3d

// double x = 1;
inline void ProtobufTranslation3d::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline double ProtobufTranslation3d::x() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTranslation3d.x)
  return _internal_x();
}
inline void ProtobufTranslation3d::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTranslation3d.x)
}
inline double ProtobufTranslation3d::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void ProtobufTranslation3d::_internal_set_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// double y = 2;
inline void ProtobufTranslation3d::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline double ProtobufTranslation3d::y() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTranslation3d.y)
  return _internal_y();
}
inline void ProtobufTranslation3d::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTranslation3d.y)
}
inline double ProtobufTranslation3d::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void ProtobufTranslation3d::_internal_set_y(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// double z = 3;
inline void ProtobufTranslation3d::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
}
inline double ProtobufTranslation3d::z() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTranslation3d.z)
  return _internal_z();
}
inline void ProtobufTranslation3d::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTranslation3d.z)
}
inline double ProtobufTranslation3d::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void ProtobufTranslation3d::_internal_set_z(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// ProtobufQuaternion

// double w = 1;
inline void ProtobufQuaternion::clear_w() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.w_ = 0;
}
inline double ProtobufQuaternion::w() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufQuaternion.w)
  return _internal_w();
}
inline void ProtobufQuaternion::set_w(double value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufQuaternion.w)
}
inline double ProtobufQuaternion::_internal_w() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.w_;
}
inline void ProtobufQuaternion::_internal_set_w(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.w_ = value;
}

// double x = 2;
inline void ProtobufQuaternion::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline double ProtobufQuaternion::x() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufQuaternion.x)
  return _internal_x();
}
inline void ProtobufQuaternion::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufQuaternion.x)
}
inline double ProtobufQuaternion::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void ProtobufQuaternion::_internal_set_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// double y = 3;
inline void ProtobufQuaternion::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline double ProtobufQuaternion::y() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufQuaternion.y)
  return _internal_y();
}
inline void ProtobufQuaternion::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufQuaternion.y)
}
inline double ProtobufQuaternion::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void ProtobufQuaternion::_internal_set_y(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// double z = 4;
inline void ProtobufQuaternion::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
}
inline double ProtobufQuaternion::z() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufQuaternion.z)
  return _internal_z();
}
inline void ProtobufQuaternion::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufQuaternion.z)
}
inline double ProtobufQuaternion::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void ProtobufQuaternion::_internal_set_z(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// ProtobufRotation3d

// .wpi.proto.ProtobufQuaternion q = 1;
inline bool ProtobufRotation3d::has_q() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.q_ != nullptr);
  return value;
}
inline void ProtobufRotation3d::clear_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.q_ != nullptr) _impl_.q_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::wpi::proto::ProtobufQuaternion& ProtobufRotation3d::_internal_q() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::wpi::proto::ProtobufQuaternion* p = _impl_.q_;
  return p != nullptr ? *p : reinterpret_cast<const ::wpi::proto::ProtobufQuaternion&>(::wpi::proto::_ProtobufQuaternion_default_instance_);
}
inline const ::wpi::proto::ProtobufQuaternion& ProtobufRotation3d::q() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufRotation3d.q)
  return _internal_q();
}
inline void ProtobufRotation3d::unsafe_arena_set_allocated_q(::wpi::proto::ProtobufQuaternion* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.q_);
  }
  _impl_.q_ = reinterpret_cast<::wpi::proto::ProtobufQuaternion*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wpi.proto.ProtobufRotation3d.q)
}
inline ::wpi::proto::ProtobufQuaternion* ProtobufRotation3d::release_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wpi::proto::ProtobufQuaternion* released = _impl_.q_;
  _impl_.q_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::wpi::proto::ProtobufQuaternion* ProtobufRotation3d::unsafe_arena_release_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:wpi.proto.ProtobufRotation3d.q)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wpi::proto::ProtobufQuaternion* temp = _impl_.q_;
  _impl_.q_ = nullptr;
  return temp;
}
inline ::wpi::proto::ProtobufQuaternion* ProtobufRotation3d::_internal_mutable_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.q_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::wpi::proto::ProtobufQuaternion>(GetArena());
    _impl_.q_ = reinterpret_cast<::wpi::proto::ProtobufQuaternion*>(p);
  }
  return _impl_.q_;
}
inline ::wpi::proto::ProtobufQuaternion* ProtobufRotation3d::mutable_q() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::wpi::proto::ProtobufQuaternion* _msg = _internal_mutable_q();
  // @@protoc_insertion_point(field_mutable:wpi.proto.ProtobufRotation3d.q)
  return _msg;
}
inline void ProtobufRotation3d::set_allocated_q(::wpi::proto::ProtobufQuaternion* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.q_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.q_ = reinterpret_cast<::wpi::proto::ProtobufQuaternion*>(value);
  // @@protoc_insertion_point(field_set_allocated:wpi.proto.ProtobufRotation3d.q)
}

// -------------------------------------------------------------------

// ProtobufPose3d

// .wpi.proto.ProtobufTranslation3d translation = 1;
inline bool ProtobufPose3d::has_translation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.translation_ != nullptr);
  return value;
}
inline void ProtobufPose3d::clear_translation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.translation_ != nullptr) _impl_.translation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::wpi::proto::ProtobufTranslation3d& ProtobufPose3d::_internal_translation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::wpi::proto::ProtobufTranslation3d* p = _impl_.translation_;
  return p != nullptr ? *p : reinterpret_cast<const ::wpi::proto::ProtobufTranslation3d&>(::wpi::proto::_ProtobufTranslation3d_default_instance_);
}
inline const ::wpi::proto::ProtobufTranslation3d& ProtobufPose3d::translation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufPose3d.translation)
  return _internal_translation();
}
inline void ProtobufPose3d::unsafe_arena_set_allocated_translation(::wpi::proto::ProtobufTranslation3d* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.translation_);
  }
  _impl_.translation_ = reinterpret_cast<::wpi::proto::ProtobufTranslation3d*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wpi.proto.ProtobufPose3d.translation)
}
inline ::wpi::proto::ProtobufTranslation3d* ProtobufPose3d::release_translation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wpi::proto::ProtobufTranslation3d* released = _impl_.translation_;
  _impl_.translation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::wpi::proto::ProtobufTranslation3d* ProtobufPose3d::unsafe_arena_release_translation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:wpi.proto.ProtobufPose3d.translation)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wpi::proto::ProtobufTranslation3d* temp = _impl_.translation_;
  _impl_.translation_ = nullptr;
  return temp;
}
inline ::wpi::proto::ProtobufTranslation3d* ProtobufPose3d::_internal_mutable_translation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.translation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::wpi::proto::ProtobufTranslation3d>(GetArena());
    _impl_.translation_ = reinterpret_cast<::wpi::proto::ProtobufTranslation3d*>(p);
  }
  return _impl_.translation_;
}
inline ::wpi::proto::ProtobufTranslation3d* ProtobufPose3d::mutable_translation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::wpi::proto::ProtobufTranslation3d* _msg = _internal_mutable_translation();
  // @@protoc_insertion_point(field_mutable:wpi.proto.ProtobufPose3d.translation)
  return _msg;
}
inline void ProtobufPose3d::set_allocated_translation(::wpi::proto::ProtobufTranslation3d* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.translation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.translation_ = reinterpret_cast<::wpi::proto::ProtobufTranslation3d*>(value);
  // @@protoc_insertion_point(field_set_allocated:wpi.proto.ProtobufPose3d.translation)
}

// .wpi.proto.ProtobufRotation3d rotation = 2;
inline bool ProtobufPose3d::has_rotation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.rotation_ != nullptr);
  return value;
}
inline void ProtobufPose3d::clear_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.rotation_ != nullptr) _impl_.rotation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::wpi::proto::ProtobufRotation3d& ProtobufPose3d::_internal_rotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::wpi::proto::ProtobufRotation3d* p = _impl_.rotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::wpi::proto::ProtobufRotation3d&>(::wpi::proto::_ProtobufRotation3d_default_instance_);
}
inline const ::wpi::proto::ProtobufRotation3d& ProtobufPose3d::rotation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufPose3d.rotation)
  return _internal_rotation();
}
inline void ProtobufPose3d::unsafe_arena_set_allocated_rotation(::wpi::proto::ProtobufRotation3d* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.rotation_);
  }
  _impl_.rotation_ = reinterpret_cast<::wpi::proto::ProtobufRotation3d*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wpi.proto.ProtobufPose3d.rotation)
}
inline ::wpi::proto::ProtobufRotation3d* ProtobufPose3d::release_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::wpi::proto::ProtobufRotation3d* released = _impl_.rotation_;
  _impl_.rotation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::wpi::proto::ProtobufRotation3d* ProtobufPose3d::unsafe_arena_release_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:wpi.proto.ProtobufPose3d.rotation)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::wpi::proto::ProtobufRotation3d* temp = _impl_.rotation_;
  _impl_.rotation_ = nullptr;
  return temp;
}
inline ::wpi::proto::ProtobufRotation3d* ProtobufPose3d::_internal_mutable_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.rotation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::wpi::proto::ProtobufRotation3d>(GetArena());
    _impl_.rotation_ = reinterpret_cast<::wpi::proto::ProtobufRotation3d*>(p);
  }
  return _impl_.rotation_;
}
inline ::wpi::proto::ProtobufRotation3d* ProtobufPose3d::mutable_rotation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::wpi::proto::ProtobufRotation3d* _msg = _internal_mutable_rotation();
  // @@protoc_insertion_point(field_mutable:wpi.proto.ProtobufPose3d.rotation)
  return _msg;
}
inline void ProtobufPose3d::set_allocated_rotation(::wpi::proto::ProtobufRotation3d* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.rotation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.rotation_ = reinterpret_cast<::wpi::proto::ProtobufRotation3d*>(value);
  // @@protoc_insertion_point(field_set_allocated:wpi.proto.ProtobufPose3d.rotation)
}

// -------------------------------------------------------------------

// ProtobufTransform3d

// .wpi.proto.ProtobufTranslation3d translation = 1;
inline bool ProtobufTransform3d::has_translation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.translation_ != nullptr);
  return value;
}
inline void ProtobufTransform3d::clear_translation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.translation_ != nullptr) _impl_.translation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::wpi::proto::ProtobufTranslation3d& ProtobufTransform3d::_internal_translation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::wpi::proto::ProtobufTranslation3d* p = _impl_.translation_;
  return p != nullptr ? *p : reinterpret_cast<const ::wpi::proto::ProtobufTranslation3d&>(::wpi::proto::_ProtobufTranslation3d_default_instance_);
}
inline const ::wpi::proto::ProtobufTranslation3d& ProtobufTransform3d::translation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTransform3d.translation)
  return _internal_translation();
}
inline void ProtobufTransform3d::unsafe_arena_set_allocated_translation(::wpi::proto::ProtobufTranslation3d* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.translation_);
  }
  _impl_.translation_ = reinterpret_cast<::wpi::proto::ProtobufTranslation3d*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wpi.proto.ProtobufTransform3d.translation)
}
inline ::wpi::proto::ProtobufTranslation3d* ProtobufTransform3d::release_translation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wpi::proto::ProtobufTranslation3d* released = _impl_.translation_;
  _impl_.translation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::wpi::proto::ProtobufTranslation3d* ProtobufTransform3d::unsafe_arena_release_translation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:wpi.proto.ProtobufTransform3d.translation)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::wpi::proto::ProtobufTranslation3d* temp = _impl_.translation_;
  _impl_.translation_ = nullptr;
  return temp;
}
inline ::wpi::proto::ProtobufTranslation3d* ProtobufTransform3d::_internal_mutable_translation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.translation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::wpi::proto::ProtobufTranslation3d>(GetArena());
    _impl_.translation_ = reinterpret_cast<::wpi::proto::ProtobufTranslation3d*>(p);
  }
  return _impl_.translation_;
}
inline ::wpi::proto::ProtobufTranslation3d* ProtobufTransform3d::mutable_translation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::wpi::proto::ProtobufTranslation3d* _msg = _internal_mutable_translation();
  // @@protoc_insertion_point(field_mutable:wpi.proto.ProtobufTransform3d.translation)
  return _msg;
}
inline void ProtobufTransform3d::set_allocated_translation(::wpi::proto::ProtobufTranslation3d* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.translation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.translation_ = reinterpret_cast<::wpi::proto::ProtobufTranslation3d*>(value);
  // @@protoc_insertion_point(field_set_allocated:wpi.proto.ProtobufTransform3d.translation)
}

// .wpi.proto.ProtobufRotation3d rotation = 2;
inline bool ProtobufTransform3d::has_rotation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.rotation_ != nullptr);
  return value;
}
inline void ProtobufTransform3d::clear_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.rotation_ != nullptr) _impl_.rotation_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::wpi::proto::ProtobufRotation3d& ProtobufTransform3d::_internal_rotation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::wpi::proto::ProtobufRotation3d* p = _impl_.rotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::wpi::proto::ProtobufRotation3d&>(::wpi::proto::_ProtobufRotation3d_default_instance_);
}
inline const ::wpi::proto::ProtobufRotation3d& ProtobufTransform3d::rotation() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTransform3d.rotation)
  return _internal_rotation();
}
inline void ProtobufTransform3d::unsafe_arena_set_allocated_rotation(::wpi::proto::ProtobufRotation3d* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.rotation_);
  }
  _impl_.rotation_ = reinterpret_cast<::wpi::proto::ProtobufRotation3d*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:wpi.proto.ProtobufTransform3d.rotation)
}
inline ::wpi::proto::ProtobufRotation3d* ProtobufTransform3d::release_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::wpi::proto::ProtobufRotation3d* released = _impl_.rotation_;
  _impl_.rotation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::wpi::proto::ProtobufRotation3d* ProtobufTransform3d::unsafe_arena_release_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:wpi.proto.ProtobufTransform3d.rotation)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::wpi::proto::ProtobufRotation3d* temp = _impl_.rotation_;
  _impl_.rotation_ = nullptr;
  return temp;
}
inline ::wpi::proto::ProtobufRotation3d* ProtobufTransform3d::_internal_mutable_rotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.rotation_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::wpi::proto::ProtobufRotation3d>(GetArena());
    _impl_.rotation_ = reinterpret_cast<::wpi::proto::ProtobufRotation3d*>(p);
  }
  return _impl_.rotation_;
}
inline ::wpi::proto::ProtobufRotation3d* ProtobufTransform3d::mutable_rotation() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::wpi::proto::ProtobufRotation3d* _msg = _internal_mutable_rotation();
  // @@protoc_insertion_point(field_mutable:wpi.proto.ProtobufTransform3d.rotation)
  return _msg;
}
inline void ProtobufTransform3d::set_allocated_rotation(::wpi::proto::ProtobufRotation3d* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.rotation_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.rotation_ = reinterpret_cast<::wpi::proto::ProtobufRotation3d*>(value);
  // @@protoc_insertion_point(field_set_allocated:wpi.proto.ProtobufTransform3d.rotation)
}

// -------------------------------------------------------------------

// ProtobufTwist3d

// double dx = 1;
inline void ProtobufTwist3d::clear_dx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dx_ = 0;
}
inline double ProtobufTwist3d::dx() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTwist3d.dx)
  return _internal_dx();
}
inline void ProtobufTwist3d::set_dx(double value) {
  _internal_set_dx(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTwist3d.dx)
}
inline double ProtobufTwist3d::_internal_dx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dx_;
}
inline void ProtobufTwist3d::_internal_set_dx(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dx_ = value;
}

// double dy = 2;
inline void ProtobufTwist3d::clear_dy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dy_ = 0;
}
inline double ProtobufTwist3d::dy() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTwist3d.dy)
  return _internal_dy();
}
inline void ProtobufTwist3d::set_dy(double value) {
  _internal_set_dy(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTwist3d.dy)
}
inline double ProtobufTwist3d::_internal_dy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dy_;
}
inline void ProtobufTwist3d::_internal_set_dy(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dy_ = value;
}

// double dz = 3;
inline void ProtobufTwist3d::clear_dz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dz_ = 0;
}
inline double ProtobufTwist3d::dz() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTwist3d.dz)
  return _internal_dz();
}
inline void ProtobufTwist3d::set_dz(double value) {
  _internal_set_dz(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTwist3d.dz)
}
inline double ProtobufTwist3d::_internal_dz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dz_;
}
inline void ProtobufTwist3d::_internal_set_dz(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dz_ = value;
}

// double rx = 4;
inline void ProtobufTwist3d::clear_rx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_ = 0;
}
inline double ProtobufTwist3d::rx() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTwist3d.rx)
  return _internal_rx();
}
inline void ProtobufTwist3d::set_rx(double value) {
  _internal_set_rx(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTwist3d.rx)
}
inline double ProtobufTwist3d::_internal_rx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_;
}
inline void ProtobufTwist3d::_internal_set_rx(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_ = value;
}

// double ry = 5;
inline void ProtobufTwist3d::clear_ry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ry_ = 0;
}
inline double ProtobufTwist3d::ry() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTwist3d.ry)
  return _internal_ry();
}
inline void ProtobufTwist3d::set_ry(double value) {
  _internal_set_ry(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTwist3d.ry)
}
inline double ProtobufTwist3d::_internal_ry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ry_;
}
inline void ProtobufTwist3d::_internal_set_ry(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ry_ = value;
}

// double rz = 6;
inline void ProtobufTwist3d::clear_rz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rz_ = 0;
}
inline double ProtobufTwist3d::rz() const {
  // @@protoc_insertion_point(field_get:wpi.proto.ProtobufTwist3d.rz)
  return _internal_rz();
}
inline void ProtobufTwist3d::set_rz(double value) {
  _internal_set_rz(value);
  // @@protoc_insertion_point(field_set:wpi.proto.ProtobufTwist3d.rz)
}
inline double ProtobufTwist3d::_internal_rz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rz_;
}
inline void ProtobufTwist3d::_internal_set_rz(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rz_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace wpi


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_geometry3d_2eproto_2epb_2eh
